/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.BookBLL;
import  Entity.Distributor;
import DAL.DistributorDAL;
import  Utilties.ControlFormat;
import BLL.DistributorBLL;
import BLL.BookReceiptBLL;
import BLL.BookReceiptInfoBLL;
import Entity.Book;
import Entity.BookReceipt;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author STIREN
 */
public class fImportBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form f
     */
    private int flag=0;
    ControlFormat control =new ControlFormat();
    DistributorBLL distributorBLL=new DistributorBLL();
    BookReceiptBLL bookReceiptBLL=new BookReceiptBLL();
    BookBLL bookbll =new BookBLL();
    BookReceiptInfoBLL bookReceiptInfoBLL =new BookReceiptInfoBLL();
    public fImportBook() {
        initComponents();
        Toolkit tk =Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();
        jPanel1.setSize(x, y);
        jPanel3.setSize(x, y);
        jLabel6.setSize((int)jPanel1.getSize().getWidth(), (int)jPanel1.getSize().getHeight());
        control.bindingDistributor(jTableDistributorInfo,distributorBLL.LoadDistributor());
        control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
        //control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.LoadBookReceiptInfo());
        control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
        Date date =new Date();
        jDateChooserReceipt.setDate(date);
        cbNameDistributorReceipt.removeAllItems();
        for(Distributor distributor: distributorBLL.LoadDistributor())
        {
            cbNameDistributorReceipt.addItem(distributor.getNameDistributor());
        }
       
        btnSaveDistributorInfo.setEnabled(false);
        btnSaveReceipt.setEnabled(false);
        btnSaveReceiptInfo.setEnabled(false);
        jTableDistributorInfo.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        txfNameDistributorInfo.setEnabled(false);
        txfAddressDistributorInfo.setEnabled(false);
        txfPhoneDistributorInfo.setEnabled(false);
        jTableDistributorInfo.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        jTableReceipt.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        jTableReceiptInfo.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        jTableBook.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        jDateChooserReceipt.setEnabled(false);
        cbNameDistributorReceipt.setEnabled(false);
        txfNameBook.setEnabled(false);
        txfAmountReceiptInfo.setEnabled(false);
        txfCost.setEnabled(false);
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txfSearchDistributor = new javax.swing.JTextField();
        btnSearchDistributorReceipt = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfIDDistributorInfo = new javax.swing.JTextField();
        txfNameDistributorInfo = new javax.swing.JTextField();
        txfAddressDistributorInfo = new javax.swing.JTextField();
        txfPhoneDistributorInfo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAddDistributorInfo = new javax.swing.JButton();
        btnEditDistributorInfo = new javax.swing.JButton();
        btnSaveDistributorInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDistributorInfo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnSaveReceiptInfo = new javax.swing.JButton();
        btnDelReceiptInfo = new javax.swing.JButton();
        btnEditReceiptInfo = new javax.swing.JButton();
        btnAddReceiptInfo = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txfAmountReceiptInfo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txfAmount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txfCost = new javax.swing.JTextField();
        txfNameBook = new javax.swing.JTextField();
        txfIDReceiptInfo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReceiptInfo = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfIDReceipt = new javax.swing.JTextField();
        jDateChooserReceipt = new com.toedter.calendar.JDateChooser();
        cbNameDistributorReceipt = new javax.swing.JComboBox<>();
        txfTotalReceipt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnAddReceipt = new javax.swing.JButton();
        btnEditReceipt = new javax.swing.JButton();
        btnSaveReceipt = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReceipt = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableBook = new javax.swing.JTable();
        txfSearchBook = new javax.swing.JTextField();
        btnSearchBook = new javax.swing.JButton();
        txfSearchReceipt1 = new javax.swing.JTextField();
        btnSearchReceipt1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaImport = new javax.swing.JTextArea();

        setClosable(true);

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÍ THÔNG TIN NHÀ CUNG CẤP SÁCH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(159, 53, 647, 37);

        jPanel4.setOpaque(false);

        txfSearchDistributor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchDistributorReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchDistributorReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchDistributorReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btnSearchDistributorReceipt.setText("Tìm kiếm");
        btnSearchDistributorReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDistributorReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfSearchDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnSearchDistributorReceipt)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txfSearchDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchDistributorReceipt)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 101, 430, 70);

        jPanel5.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Mã nhà cung cấp");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Tên nhà cung cấp");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Số điện thoại");

        txfIDDistributorInfo.setEditable(false);
        txfIDDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfNameDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfNameDistributorInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfNameDistributorInfoKeyTyped(evt);
            }
        });

        txfAddressDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfPhoneDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfPhoneDistributorInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfPhoneDistributorInfoKeyTyped(evt);
            }
        });

        jPanel6.setOpaque(false);

        btnAddDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddDistributorInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnAddDistributorInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        btnAddDistributorInfo.setText("THÊM");
        btnAddDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDistributorInfoActionPerformed(evt);
            }
        });

        btnEditDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditDistributorInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnEditDistributorInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tools.png"))); // NOI18N
        btnEditDistributorInfo.setText("CẬP NHẬT");
        btnEditDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDistributorInfoActionPerformed(evt);
            }
        });

        btnSaveDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveDistributorInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveDistributorInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/folder.png"))); // NOI18N
        btnSaveDistributorInfo.setText("LƯU");
        btnSaveDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDistributorInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDistributorInfo)
                .addGap(42, 42, 42)
                .addComponent(btnEditDistributorInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddDistributorInfo))
                    .addComponent(btnEditDistributorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaveDistributorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfNameDistributorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfIDDistributorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                    .addComponent(txfAddressDistributorInfo)
                                    .addComponent(txfPhoneDistributorInfo))))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfIDDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfNameDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfAddressDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfPhoneDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 193, 470, 320);

        jTableDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableDistributorInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại", "Email"
            }
        ));
        jTableDistributorInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDistributorInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDistributorInfo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 110, 830, 450);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1460, 720);

        jTabbedPane1.addTab("Nhà cung cấp sách", jPanel1);

        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("QUẢN LÝ NHẬP SÁCH");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(464, 11, 323, 37);

        jPanel10.setOpaque(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel10);
        jPanel10.setBounds(1394, 110, 454, 5);

        jPanel12.setOpaque(false);

        btnSaveReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveReceiptInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/folder.png"))); // NOI18N
        btnSaveReceiptInfo.setText("LƯU");
        btnSaveReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveReceiptInfoActionPerformed(evt);
            }
        });

        btnDelReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnDelReceiptInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rubbish-bin.png"))); // NOI18N
        btnDelReceiptInfo.setText("XÓA");
        btnDelReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelReceiptInfoActionPerformed(evt);
            }
        });

        btnEditReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnEditReceiptInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tools.png"))); // NOI18N
        btnEditReceiptInfo.setText("CẬP NHẬT");
        btnEditReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditReceiptInfoActionPerformed(evt);
            }
        });

        btnAddReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnAddReceiptInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        btnAddReceiptInfo.setText("THÊM");
        btnAddReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReceiptInfoActionPerformed(evt);
            }
        });

        jPanel11.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Số phiếu nhập");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Tên sách");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Số lượng");

        txfAmountReceiptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfAmountReceiptInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfAmountReceiptInfoKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Thành tiền");

        txfAmount.setEditable(false);
        txfAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Giá nhập");

        txfCost.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfCostKeyTyped(evt);
            }
        });

        txfNameBook.setEditable(false);
        txfNameBook.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfIDReceiptInfo.setEditable(false);
        txfIDReceiptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(49, 49, 49)
                        .addComponent(txfAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txfNameBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txfIDReceiptInfo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfAmountReceiptInfo)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(63, 63, 63)
                        .addComponent(txfCost)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txfIDReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(txfNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16))
                    .addComponent(txfAmountReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txfCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditReceiptInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveReceiptInfo)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveReceiptInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEditReceiptInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelReceiptInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddReceiptInfo))
                .addGap(299, 299, 299))
        );

        jPanel3.add(jPanel12);
        jPanel12.setBounds(0, 290, 490, 590);

        jTableReceiptInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableReceiptInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Số lượng", "Title 3", "Thành tiền"
            }
        ));
        jTableReceiptInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceiptInfoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableReceiptInfo);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(490, 329, 887, 270);

        jPanel8.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Ngày nhập");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Tổng tiền");

        txfIDReceipt.setEditable(false);
        txfIDReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jDateChooserReceipt.setDateFormatString("dd-MM-yyyy");
        jDateChooserReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cbNameDistributorReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfTotalReceipt.setEditable(false);
        txfTotalReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Tên nhà cung cấp");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Số phiếu nhập");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(cbNameDistributorReceipt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfIDReceipt)
                            .addComponent(txfTotalReceipt)))
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfIDReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(jDateChooserReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNameDistributorReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txfTotalReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 92, 460, 168);

        jPanel9.setOpaque(false);

        btnAddReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnAddReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        btnAddReceipt.setText("THÊM");
        btnAddReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReceiptActionPerformed(evt);
            }
        });

        btnEditReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnEditReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tools.png"))); // NOI18N
        btnEditReceipt.setText("CẬP NHẬT");
        btnEditReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditReceiptActionPerformed(evt);
            }
        });

        btnSaveReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/folder.png"))); // NOI18N
        btnSaveReceipt.setText("LƯU");
        btnSaveReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveReceiptActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(0, 0, 204));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/folder.png"))); // NOI18N
        btnPrint.setText("IN");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnAddReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnPrint)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveReceipt)
                    .addComponent(btnPrint))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 260, 510, 53);

        jTableReceipt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số phiếu nhập", "Ngày nhập", "Mã nhà cung cấp", "Tên nhà cung cấp", "Tổng tiền"
            }
        ));
        jTableReceipt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableReceipt.setAutoscrolls(false);
        jTableReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceiptMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableReceipt);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(490, 100, 452, 220);

        jTableBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Giá nhập"
            }
        ));
        jTableBook.setAutoscrolls(false);
        jTableBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBookMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableBook);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(948, 101, 403, 220);

        txfSearchBook.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSearchBookActionPerformed(evt);
            }
        });
        jPanel3.add(txfSearchBook);
        txfSearchBook.setBounds(950, 60, 205, 25);

        btnSearchBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchBook.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btnSearchBook.setText("Tìm kiếm");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearchBook);
        btnSearchBook.setBounds(1170, 60, 130, 30);

        txfSearchReceipt1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel3.add(txfSearchReceipt1);
        txfSearchReceipt1.setBounds(490, 60, 232, 25);

        btnSearchReceipt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchReceipt1.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchReceipt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btnSearchReceipt1.setText("Tìm kiếm");
        btnSearchReceipt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReceipt1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearchReceipt1);
        btnSearchReceipt1.setBounds(760, 60, 130, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 0, 1670, 890);

        txaImport.setColumns(20);
        txaImport.setRows(5);
        jScrollPane5.setViewportView(txaImport);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(988, 228, 100, 18);

        jTabbedPane1.addTab("Nhập sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1317, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDistributorInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDistributorInfoMouseClicked
        // TODO add your handling code here:
        txfNameDistributorInfo.setEnabled(false);
        txfAddressDistributorInfo.setEnabled(false);
        txfPhoneDistributorInfo.setEnabled(false);
        int row=jTableDistributorInfo.getSelectedRow();
        txfIDDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 0).toString());
        txfNameDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 1).toString());
        txfAddressDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 2).toString());
        txfPhoneDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTableDistributorInfoMouseClicked

    private void btnSaveDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDistributorInfoActionPerformed
        // TODO add your handling code here:
        if(flag==1)
        {
            if(InsertDistributor()==true)
            {
                control.bindingDistributor(jTableDistributorInfo, distributorBLL.LoadDistributor());
                txfNameDistributorInfo.setEnabled(false);
                txfAddressDistributorInfo.setEnabled(false);
                txfPhoneDistributorInfo.setEnabled(false);
            }
            btnAddDistributorInfo.setEnabled(true);
            btnEditDistributorInfo.setEnabled(true);
            btnSaveDistributorInfo.setEnabled(false);
        }
        if(flag==2)
        {
            if(UpdateDistributor()==true)
            {
                control.bindingDistributor(jTableDistributorInfo, distributorBLL.LoadDistributor());
                txfNameDistributorInfo.setEnabled(false);
                txfAddressDistributorInfo.setEnabled(false);
                txfPhoneDistributorInfo.setEnabled(false);
                ClearTextDistibutor();
            }
            btnAddDistributorInfo.setEnabled(true);
            btnEditDistributorInfo.setEnabled(true);
            btnSaveDistributorInfo.setEnabled(false);
        }
        cbNameDistributorReceipt.removeAllItems();
        for(Distributor distributor: distributorBLL.LoadDistributor())
        {
            cbNameDistributorReceipt.addItem(distributor.getNameDistributor());
        }
    }//GEN-LAST:event_btnSaveDistributorInfoActionPerformed

    private void btnEditDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDistributorInfoActionPerformed
        // TODO add your handling code here:
        txfNameDistributorInfo.setEnabled(true);
        txfAddressDistributorInfo.setEnabled(true);
        txfPhoneDistributorInfo.setEnabled(true);
        btnAddDistributorInfo.setEnabled(false);
        btnEditDistributorInfo.setEnabled(false);
        btnSaveDistributorInfo.setEnabled(true);
        flag=2;
    }//GEN-LAST:event_btnEditDistributorInfoActionPerformed

    private void btnAddDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDistributorInfoActionPerformed
        // TODO add your handling code here:
        ClearTextDistibutor();
        txfNameDistributorInfo.setEnabled(true);
        txfAddressDistributorInfo.setEnabled(true);
        txfPhoneDistributorInfo.setEnabled(true);
        btnAddDistributorInfo.setEnabled(false);
        btnEditDistributorInfo.setEnabled(false);
        btnSaveDistributorInfo.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddDistributorInfoActionPerformed

    private void txfPhoneDistributorInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfPhoneDistributorInfoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) || txfPhoneDistributorInfo.getText().length() >= 10)
        evt.consume();
    }//GEN-LAST:event_txfPhoneDistributorInfoKeyTyped

    private void btnSearchDistributorReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDistributorReceiptActionPerformed
        // TODO add your handling code here:
        String key=txfSearchDistributor.getText();
        control.bindingDistributor(jTableDistributorInfo, distributorBLL.SearchDistributor(key));
        txfSearchDistributor.setText("");
    }//GEN-LAST:event_btnSearchDistributorReceiptActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        // TODO add your handling code here:
        String key =txfSearchBook.getText();
        control.bindingIDNameBook(jTableBook, bookbll.SearchBookImport(key));
        txfSearchBook.setText("");
        if(jTableBook.getRowCount()==0)
        {
            fListBook f =new fListBook();
            int x = (int) tk.getScreenSize().getWidth();
            int y = (int) tk.getScreenSize().getHeight();
            f.setSize(x, y);
            jTabbedPane1.add(f);
            f.setVisible(true);
            control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());

        }
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void jTableBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBookMouseClicked
        // TODO add your handling code here:
        int row=jTableBook.getSelectedRow();
        txfNameBook.setText(jTableBook.getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTableBookMouseClicked

    private void jTableReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceiptMouseClicked
        // TODO add your handling code here:
        jDateChooserReceipt.setEnabled(false);
        cbNameDistributorReceipt.setEnabled(false);
        int row=jTableReceipt.getSelectedRow();
        txfIDReceipt.setText(jTableReceipt.getValueAt(row, 0).toString());
        int IDBooReceipt=Integer.parseInt(txfIDReceipt.getText().toString());
        txfIDReceiptInfo.setText(jTableReceipt.getValueAt(row, 0).toString());
        jDateChooserReceipt.setDate((Date)jTableReceipt.getModel().getValueAt(row, 1));
        String NameDistributor =jTableReceipt.getValueAt(row, 2).toString();
        if(jTableReceipt.getValueAt(row, 2).toString().equals(NameDistributor))
        cbNameDistributorReceipt.setSelectedItem(NameDistributor);
        txfTotalReceipt.setText(jTableReceipt.getValueAt(row, 3).toString());
        control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.SearchBookReceiptInfo(IDBooReceipt));
    }//GEN-LAST:event_jTableReceiptMouseClicked

    private void btnSearchReceipt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchReceipt1ActionPerformed
        // TODO add your handling code here:
        String key =txfSearchReceipt1.getText().toString();
        control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.SearchBookReceipt(key));
        txfSearchReceipt1.setText("");
    }//GEN-LAST:event_btnSearchReceipt1ActionPerformed

    private void btnSaveReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveReceiptActionPerformed
        // TODO add your handling code here:
        if(flag==4)
        {
            if(InsertBookReceipt()==true)
            {
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                jDateChooserReceipt.setEnabled(false);
                cbNameDistributorReceipt.setEnabled(false);
            }
            btnAddReceipt.setEnabled(true);
            btnEditReceipt.setEnabled(true);
            btnSaveReceipt.setEnabled(false);
        }
        if(flag==5)
        {
            if(UpdateBookReceipt()==true)
            {
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                jDateChooserReceipt.setEnabled(false);
                cbNameDistributorReceipt.setEnabled(false);
            }
            btnAddReceipt.setEnabled(true);
            btnEditReceipt.setEnabled(true);
            btnSaveReceipt.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveReceiptActionPerformed

    private void btnEditReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditReceiptActionPerformed
        // TODO add your handling code here:
        jDateChooserReceipt.setEnabled(true);
        cbNameDistributorReceipt.setEnabled(true);
        btnAddReceipt.setEnabled(false);
        btnEditReceipt.setEnabled(false);
        btnSaveReceipt.setEnabled(true);
        flag=5;
    }//GEN-LAST:event_btnEditReceiptActionPerformed

    private void btnAddReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReceiptActionPerformed
        // TODO add your handling code here:
        ClearTextBookReceipt();
        jDateChooserReceipt.setEnabled(true);
        cbNameDistributorReceipt.setEnabled(true);
        txfIDReceiptInfo.setText(String.valueOf(txfIDReceipt.getText()));
        btnAddReceipt.setEnabled(false);
        btnEditReceipt.setEnabled(false);
        btnSaveReceipt.setEnabled(true);
        flag=4;
    }//GEN-LAST:event_btnAddReceiptActionPerformed

    private void jTableReceiptInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceiptInfoMouseClicked
        // TODO add your handling code here:
        txfNameBook.setEnabled(false);
        txfAmountReceiptInfo.setEnabled(false);
        txfCost.setEnabled(false);
        int row=jTableReceiptInfo.getSelectedRow();
        txfNameBook.setText(jTableReceiptInfo.getValueAt(row, 0).toString());
        txfAmountReceiptInfo.setText(jTableReceiptInfo.getValueAt(row, 1).toString());
        txfCost.setText(jTableReceiptInfo.getValueAt(row, 2).toString());
        txfAmount.setText(jTableReceiptInfo.getValueAt(row,3).toString());
    }//GEN-LAST:event_jTableReceiptInfoMouseClicked

    private void txfCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfCostKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (txfCost.getText().equals(""))
        dot = false;
        if (dot == false){
            if (vChar == '.')
            dot = true;
            else if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
        else {
            if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
    }//GEN-LAST:event_txfCostKeyTyped

    private void txfAmountReceiptInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfAmountReceiptInfoKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (txfAmountReceiptInfo.getText().equals(""))
        dot = false;
        if (dot == false){
            if (vChar == '.')
            dot = true;
            else if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
        else {
            if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
    }//GEN-LAST:event_txfAmountReceiptInfoKeyTyped

    private void btnAddReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReceiptInfoActionPerformed
        // TODO add your handling code here:
        ClearTextReceiptInfo();
        txfNameBook.setEnabled(true);
        txfAmountReceiptInfo.setEnabled(true);
        txfCost.setEnabled(true);
        txfIDReceiptInfo.setText(String.valueOf(txfIDReceipt.getText()));
        btnAddReceiptInfo.setEnabled(false);
        btnEditReceiptInfo.setEnabled(false);
        btnDelReceiptInfo.setEnabled(false);
        btnSaveReceiptInfo.setEnabled(true);
        flag=7;
    }//GEN-LAST:event_btnAddReceiptInfoActionPerformed

    private void btnEditReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditReceiptInfoActionPerformed
        // TODO add your handling code here:
        txfNameBook.setEnabled(true);
        txfAmountReceiptInfo.setEnabled(true);
        txfCost.setEnabled(true);
        btnAddReceiptInfo.setEnabled(false);
        btnEditReceiptInfo.setEnabled(false);
        btnDelReceiptInfo.setEnabled(false);
        btnSaveReceiptInfo.setEnabled(true);
        flag=8;
    }//GEN-LAST:event_btnEditReceiptInfoActionPerformed

    private void btnDelReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelReceiptInfoActionPerformed
        // TODO add your handling code here:
        txfNameBook.setEnabled(true);
        txfAmountReceiptInfo.setEnabled(true);
        txfCost.setEnabled(true);
        btnAddReceiptInfo.setEnabled(false);
        btnEditReceiptInfo.setEnabled(false);
        btnDelReceiptInfo.setEnabled(false);
        btnSaveReceiptInfo.setEnabled(true);
        flag=9;
    }//GEN-LAST:event_btnDelReceiptInfoActionPerformed

    private void btnSaveReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveReceiptInfoActionPerformed
        // TODO add your handling code here:
        if(flag==7)
        {
            if(InsertBookReceiptInfo()==true)
            {
                int IDBooReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.SearchBookReceiptInfo(IDBooReceipt));
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
                int IDReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                txfTotalReceipt.setText(String.valueOf(bookReceiptBLL.getTotalReceipt(IDReceipt)));
                txfNameDistributorInfo.setText(bookReceiptBLL.getDistributor(IDReceipt));
                jDateChooserReceipt.setDate(bookReceiptBLL.getDateReceipt(IDReceipt));
                txfNameBook.setEnabled(false);
                txfAmountReceiptInfo.setEnabled(false);
                txfCost.setEnabled(false);
            }
            btnAddReceiptInfo.setEnabled(true);
            btnEditReceiptInfo.setEnabled(true);
            btnDelReceiptInfo.setEnabled(true);
            btnSaveReceiptInfo.setEnabled(false);
        }
        if(flag==8)
        {
            if(UpdateBookReceiptInfo()==true)
            {
               int IDBooReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.SearchBookReceiptInfo(IDBooReceipt));
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
                int IDReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                txfTotalReceipt.setText(String.valueOf(bookReceiptBLL.getTotalReceipt(IDReceipt)));
                txfNameDistributorInfo.setText(bookReceiptBLL.getDistributor(IDReceipt));
                jDateChooserReceipt.setDate(bookReceiptBLL.getDateReceipt(IDReceipt));
                txfNameBook.setEnabled(false);
                txfAmountReceiptInfo.setEnabled(false);
                txfCost.setEnabled(false);
            }
            btnAddReceiptInfo.setEnabled(true);
            btnEditReceiptInfo.setEnabled(true);
            btnDelReceiptInfo.setEnabled(true);
            btnSaveReceiptInfo.setEnabled(false);
        }
        if(flag==9)
        {
            if(DeleteBookReceiptInfo()==true)
            {
                int IDBooReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.SearchBookReceiptInfo(IDBooReceipt));
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
                int IDReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                txfTotalReceipt.setText(String.valueOf(bookReceiptBLL.getTotalReceipt(IDReceipt)));
                txfNameDistributorInfo.setText(bookReceiptBLL.getDistributor(IDReceipt));
                jDateChooserReceipt.setDate(bookReceiptBLL.getDateReceipt(IDReceipt));
                txfNameBook.setEnabled(false);
                txfAmountReceiptInfo.setEnabled(false);
                txfCost.setEnabled(false);
            }
            btnAddReceiptInfo.setEnabled(true);
            btnEditReceiptInfo.setEnabled(true);
            btnDelReceiptInfo.setEnabled(true);
            btnSaveReceiptInfo.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveReceiptInfoActionPerformed

    private void txfSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSearchBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSearchBookActionPerformed

    private void txfNameDistributorInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNameDistributorInfoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNameDistributorInfoKeyTyped

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        txaImport.setText("");
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        txaImport.append("\t \t  NHÀ SÁCH TYQ \n \n");
        txaImport.append("Địa chỉ: Khu phố 6, P.Linh Trung, Q.Thủ Đức, TP.Hồ Chí Minh. \n" +
            "SĐT: 0962 111 222 \n" +
            "Email: nhasachTYQ@gmail.com \n \n");
        txaImport.append("\t \t PHIẾU NHẬP SÁCH \n \n");
        int IDBookReceipt=Integer.parseInt(txfIDReceipt.getText().toString());
        txaImport.append("\nTên nhà cung cấp: "+ cbNameDistributorReceipt.getSelectedItem().toString());
        String NameDistributor =cbNameDistributorReceipt.getSelectedItem().toString();
        int IDDistributor=distributorBLL.getIDDistributor(NameDistributor);
        txaImport.append("\nĐịa chỉ: "+ distributorBLL.getAddressDistributor(IDDistributor));
        txaImport.append("\nSố điện thoại:"+distributorBLL.getPhoneDistributor(IDDistributor));
        txaImport.append("\nNgày nhập: "+df.format(jDateChooserReceipt.getDate()).toString());
        txaImport.append("\n\n\n--------------------------------------------------------------------------------------------------------------------------------\n");
        
        control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.SearchBookReceiptInfo(IDBookReceipt));
        int row = jTableReceiptInfo.getRowCount();
        int column = jTableReceiptInfo.getColumnCount();
        txaImport.append("\nTên sách \tSố lượng \t Giá nhập \t Thành tiền \n");
        txaImport.append("--------------------------------------------------------------------------------------------------------------------------------\n");

        for(int i=0; i < row; i++)
        {
            for(int j=0; j < column; j++)
            {
                txaImport.append(jTableReceiptInfo.getValueAt(i, j).toString() + "\t");
                if(j == 2)
                txaImport.append("\t");
            }
            txaImport.append("\n");
        }
        txaImport.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        txaImport.append("\nTổng tiền: " + txfTotalReceipt.getText()+" đồng" + "\n" +
            "Cám ơn quý công ty!");
        try {
            txaImport.print();
        } catch (PrinterException ex) {
            Logger.getLogger(fSales.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPrintActionPerformed
    public String chuanHoa(String str) {
        str = str.trim();
        str = str.replaceAll("\\s+", " ");
        return str;
    }
    public void ClearTextReceiptInfo()
    {
        
        txfAmountReceiptInfo.setText("");
        txfCost.setText("");
        txfAmount.setText("");
        txfNameBook.setText("");
    }    Toolkit tk = Toolkit.getDefaultToolkit();    boolean dot = false;    public void ClearTextDistibutor()
    {
        txfIDDistributorInfo.setText("");
        txfNameDistributorInfo.setText("");
        txfAddressDistributorInfo.setText("");
        txfPhoneDistributorInfo.setText("");
    }
    public boolean InsertDistributor()
    {
        String NameDistributor =txfNameDistributorInfo.getText().toString();
        String Address =txfAddressDistributorInfo.getText().toString();
        String PhoneNumber =txfPhoneDistributorInfo.getText().toString();
        if(txfNameDistributorInfo.getText().toString().equals("")|| txfPhoneDistributorInfo.getText().toString().equals("") || txfAddressDistributorInfo.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, địa chỉ, số điện thoại là bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            Address=chuanHoa(Address);
            if(distributorBLL.InsertDistributor(NameDistributor, Address, PhoneNumber))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công nhà cung cấp");
                return true;
            }   
                else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
        }
        
    }
    public boolean UpdateDistributor()
    {
        int IDDistributor=Integer.parseInt(txfIDDistributorInfo.getText().toString());
        String NameDistributor =txfNameDistributorInfo.getText().toString();
        String Address =txfAddressDistributorInfo.getText().toString();
        String PhoneNumber =txfPhoneDistributorInfo.getText().toString();
        if(txfNameDistributorInfo.getText().toString().equals("")|| txfPhoneDistributorInfo.getText().toString().equals("") || txfAddressDistributorInfo.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, địa chỉ, số điện thoại là bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            Address=chuanHoa(Address);
            if(distributorBLL.UpdateDistributor(IDDistributor,NameDistributor, Address, PhoneNumber))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công nhà cung cấp");
                return true;
            }   
                else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
        }
    }
      public void ClearTextBookReceipt()
    {
        txfIDReceipt.setText("");
        txfTotalReceipt.setText("");
        jDateChooserReceipt.setDate(new Date());
    }
    public boolean InsertBookReceipt()
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date DateReceipt=jDateChooserReceipt.getDate();
        String strDateReceipt = formatter.format(DateReceipt);
        String NameDistributor =cbNameDistributorReceipt.getSelectedItem().toString();
        int IDDistributor=distributorBLL.getIDDistributor(NameDistributor);
        if(NameDistributor.equals("") || strDateReceipt.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, ngày nhập, thành tiền là các trường bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            
            if(bookReceiptBLL.InsertBookReceipt(strDateReceipt, IDDistributor))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
            
        }
        
        
    }
    public boolean  UpdateBookReceipt()
    {
        int IDBookReceipt =Integer.parseInt(txfIDReceipt.getText().toString());
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date DateReceipt=jDateChooserReceipt.getDate();
        String strDateReceipt = formatter.format(DateReceipt);
        String NameDistributor =cbNameDistributorReceipt.getSelectedItem().toString();
        int IDDistributor=distributorBLL.getIDDistributor(NameDistributor);
        float TotalReceipt=Float.parseFloat(txfTotalReceipt.getText().toString());
        if(NameDistributor.equals("") || strDateReceipt.equals("")|| txfTotalReceipt.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, ngày nhập, thành tiền là các trường bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            if(bookReceiptBLL.UpdateBookReceipt(IDBookReceipt, strDateReceipt, IDDistributor))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
            
        }
        
    }
   
    public boolean InsertBookReceiptInfo()
    {
        
        if(txfIDReceiptInfo.getText().equals("")|| txfNameBook.getText().equals("") ||txfAmountReceiptInfo.getText().equals("")|| txfCost.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nhập thông tin chưa đầy đủ");
            return false;
        }
       else
        {
            int IDBookReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
            int row =jTableBook.getSelectedRow();
            String NameBook="";
            NameBook=jTableBook.getValueAt(row, 1).toString();
            int IDBook=bookbll.getIDBook(NameBook);
            int AmountReceipt=Integer.parseInt(txfAmountReceiptInfo.getText().toString());
            float Cost =Float.parseFloat(txfCost.getText().toString());
            if(bookReceiptInfoBLL.InsertBookReceiptInfo(IDBookReceipt, IDBook, AmountReceipt,Cost))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
        }
    }
    public boolean  UpdateBookReceiptInfo()
    {
        
        if(txfIDReceiptInfo.equals("")||txfNameBook.equals("")||txfAmountReceiptInfo.equals("")|| txfCost.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nhập thông tin chưa đầy đủ");
            return false;
        }
       else
        {
            int IDBookReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
        int row =jTableBook.getSelectedRow();
        String NameBook=txfNameBook.getText().toString();
        int IDBook=bookbll.getIDBook(NameBook);
        int AmountReceipt=Integer.parseInt(txfAmountReceiptInfo.getText());
        float Cost=Float.parseFloat(txfCost.getText());
            if(bookReceiptInfoBLL.UpdateBookReceiptInfo(IDBookReceipt, IDBook, AmountReceipt,Cost))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
        }
     
    }
    public boolean DeleteBookReceiptInfo()
    {
       int IDBookReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
       String NameBook="";//=cbNameBookReceiptInfo.getSelectedItem().toString();
       int IDBook =bookbll.getIDBook(NameBook);
       if(bookReceiptInfoBLL.DeleteBookReceiptInfo(IDBookReceipt,IDBook))
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
                return false;
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDistributorInfo;
    private javax.swing.JButton btnAddReceipt;
    private javax.swing.JButton btnAddReceiptInfo;
    private javax.swing.JButton btnDelReceiptInfo;
    private javax.swing.JButton btnEditDistributorInfo;
    private javax.swing.JButton btnEditReceipt;
    private javax.swing.JButton btnEditReceiptInfo;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSaveDistributorInfo;
    private javax.swing.JButton btnSaveReceipt;
    private javax.swing.JButton btnSaveReceiptInfo;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnSearchDistributorReceipt;
    private javax.swing.JButton btnSearchReceipt1;
    private javax.swing.JComboBox<String> cbNameDistributorReceipt;
    private com.toedter.calendar.JDateChooser jDateChooserReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBook;
    private javax.swing.JTable jTableDistributorInfo;
    private javax.swing.JTable jTableReceipt;
    private javax.swing.JTable jTableReceiptInfo;
    private javax.swing.JTextArea txaImport;
    private javax.swing.JTextField txfAddressDistributorInfo;
    private javax.swing.JTextField txfAmount;
    private javax.swing.JTextField txfAmountReceiptInfo;
    private javax.swing.JTextField txfCost;
    private javax.swing.JTextField txfIDDistributorInfo;
    private javax.swing.JTextField txfIDReceipt;
    private javax.swing.JTextField txfIDReceiptInfo;
    private javax.swing.JTextField txfNameBook;
    private javax.swing.JTextField txfNameDistributorInfo;
    private javax.swing.JTextField txfPhoneDistributorInfo;
    private javax.swing.JTextField txfSearchBook;
    private javax.swing.JTextField txfSearchDistributor;
    private javax.swing.JTextField txfSearchReceipt1;
    private javax.swing.JTextField txfTotalReceipt;
    // End of variables declaration//GEN-END:variables
}
