/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BookBLL;
import BLL.BookCategogyBLL;
import Entity.BookCategogy;
import Utilties.ControlFormat;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author STIREN
 */
public class fReportInventory extends javax.swing.JInternalFrame {

    /**
     * Creates new form fInventory
     */
    ControlFormat control = new ControlFormat();
    BookCategogyBLL categogyBLL = new BookCategogyBLL();
    BookBLL bookBLL = new BookBLL();
    String name;
    public fReportInventory() {
        initComponents();
        Toolkit tk =Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();
        btnPrintReportInventory.setEnabled(false);
        cbCategogyBookRI.removeAllItems();
        cbCategogyBookRI.addItem("Tất cả");
        for(BookCategogy bookCategogy: categogyBLL.LoadBookCategogy())
        {
            cbCategogyBookRI.addItem(bookCategogy.getNameBookCategogy());
        }
        jTableMinInventory.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        jTableTop20.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel8.setSize(x,y);
    }
    public void getUserName(String namestaff){
          name =namestaff;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMinInventory = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbCategogyBookRI = new javax.swing.JComboBox<>();
        btnReportInventory = new javax.swing.JButton();
        btnPrintReportInventory = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDChFromDate = new com.toedter.calendar.JDateChooser();
        jDChToDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTop20 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaRPInventory = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("BÁO CÁO TỒN KHO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(353, 24, 287, 37);

        jTableMinInventory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableMinInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tên thể loại", "Giá", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(jTableMinInventory);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 570, 330);

        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Loại sách");

        cbCategogyBookRI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbCategogyBookRI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiểu thuyết", "Truyện ngắn", "Tất cả", " " }));

        btnReportInventory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportInventory.setForeground(new java.awt.Color(0, 0, 204));
        btnReportInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clipboard_edit.png"))); // NOI18N
        btnReportInventory.setText("THỐNG KÊ");
        btnReportInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportInventoryActionPerformed(evt);
            }
        });

        btnPrintReportInventory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrintReportInventory.setForeground(new java.awt.Color(0, 0, 204));
        btnPrintReportInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/print.png"))); // NOI18N
        btnPrintReportInventory.setText("IN BÁO CÁO");
        btnPrintReportInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportInventoryActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Từ ngày");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Đến ngày");

        jDChFromDate.setDateFormatString("dd-MM-yyyy");
        jDChFromDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDChToDate.setDateFormatString("dd-MM-yyyy");
        jDChToDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDChFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDChToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCategogyBookRI, 0, 216, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrintReportInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbCategogyBookRI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReportInventory))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrintReportInventory)
                    .addComponent(jLabel5)
                    .addComponent(jDChFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDChToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 545, 160);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Danh sách sách có số lượng tồn dưới mức quy định");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 230, 351, 17);

        jTableTop20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableTop20.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableTop20);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(680, 260, 620, 330);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Top 20 sách bán chạy");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 230, 150, 17);

        jScrollPane3.setOpaque(false);

        txaRPInventory.setColumns(20);
        txaRPInventory.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txaRPInventory.setRows(5);
        jScrollPane3.setViewportView(txaRPInventory);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(840, 270, 68, 32);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1300, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportInventoryActionPerformed
        // TODO add your handling code here:
        btnPrintReportInventory.setEnabled(true);
        String NameBookCategory = cbCategogyBookRI.getSelectedItem().toString();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String FromDate, ToDate;
        if(jDChFromDate.getDate() == null)
            FromDate = "";
        else
            FromDate = df.format(jDChFromDate.getDate());
        if(jDChToDate.getDate() == null)
            ToDate = "";
        else
        ToDate = df.format(jDChToDate.getDate());
        
        control.bindingRPInventoryMinInventory(jTableMinInventory, bookBLL.RPInventoryMinInventory(NameBookCategory));
        control.bindingRPInventoryTop20(jTableTop20, bookBLL.RPInventoryTop20(FromDate, ToDate));
    }//GEN-LAST:event_btnReportInventoryActionPerformed

    private void btnPrintReportInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportInventoryActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String FromDate, ToDate;
        if(jDChFromDate.getDate() == null)
            FromDate = "";
        else
            FromDate = df.format(jDChFromDate.getDate());
        if(jDChToDate.getDate() == null)
            ToDate = "";
        else
        ToDate = df.format(jDChToDate.getDate());
        //MASACH, TENTHELOAI, TENSACH, TACGIA, NHAXUATBAN, NAMXUATBAN, GIANHAP, TONGSACHTON
        txaRPInventory.setText("");
        txaRPInventory.append("\t \t  NHÀ SÁCH TYQ \n \n");
        txaRPInventory.append("Địa chỉ: Khu phố 6, P.Linh Trung, Q.Thủ Đức, TP.Hồ Chí Minh. \n" +
            "SĐT: 0962 111 222 \n" +
            "Email: nhasachTYQ@gmail.com \n \n");
        txaRPInventory.append("\t \t BÁO CÁO TỒN KHO \n");
        txaRPInventory.append("\t \t (Từ ngày " + FromDate + " đến ngày " + ToDate + ") \n\n");
        txaRPInventory.append("Danh sách sách có tồn kho dưới mức quy định\n");
        txaRPInventory.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        txaRPInventory.append("Mã sách \t Tên thể loại \t Tên sách \t Tác giả \t Nhà xuất bản \t Năm xuất bản \t Giá nhập \t Tổng sách tồn \n");
        txaRPInventory.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        int row = jTableMinInventory.getRowCount();
        int column = jTableMinInventory.getColumnCount();
        for(int i=0; i < row; i++)
        {
            for(int j=0; j < column; j++)
            {
                txaRPInventory.append(jTableMinInventory.getValueAt(i, j).toString() + "\t");
//                if(j == 1)
//                    txaRPInventory.append("\t");
            }
            txaRPInventory.append("\n");
        }
        txaRPInventory.append("\n\n");
        //MASACH, TENTHELOAI, TENSACH, TACGIA, NHAXUATBAN, NAMXUATBAN, GIANHAP
        txaRPInventory.append("Top 20 sách bán chạy\n");
        txaRPInventory.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        txaRPInventory.append("Mã sách \t Tên thể loại \t Tên sách \t Tác giả \t Nhà xuất bản \t Năm xuất bản \t Giá nhập \n");
        txaRPInventory.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        int row1 = jTableTop20.getRowCount();
        int column1 = jTableTop20.getColumnCount();
        for(int i=0; i < row1; i++)
        {
            for(int j=0; j < column1; j++)
            {
                txaRPInventory.append(jTableTop20.getValueAt(i, j).toString() + "\t");
//                if(j == 1)
//                    txaRPInventory.append("\t");
            }
            txaRPInventory.append("\n");
        }
        
        txaRPInventory.append("--------------------------------------------------------------------------------------------------------------------------------\n\n");
        txaRPInventory.append("Ngày lập báo cáo: " + df.format(new Date()) + "\n");
        txaRPInventory.append("Người lập báo cáo: "+ name) ;
        try {
            txaRPInventory.print();
        } catch (PrinterException ex) {
            Logger.getLogger(fReportInventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintReportInventoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintReportInventory;
    private javax.swing.JButton btnReportInventory;
    private javax.swing.JComboBox<String> cbCategogyBookRI;
    private com.toedter.calendar.JDateChooser jDChFromDate;
    private com.toedter.calendar.JDateChooser jDChToDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableMinInventory;
    private javax.swing.JTable jTableTop20;
    private javax.swing.JTextArea txaRPInventory;
    // End of variables declaration//GEN-END:variables
}
