/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BillBLL;
import BLL.BookBLL;
import BLL.BookReceiptBLL;
import Utilties.ControlFormat;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author STIREN
 */
public class fReportRevenue extends javax.swing.JInternalFrame {

    /**
     * Creates new form fReportRevenue
     */
    ControlFormat control = new ControlFormat();
    BillBLL billBLL = new BillBLL();
    BookReceiptBLL bookReceiptBLL = new BookReceiptBLL();
    String name ;
    public fReportRevenue() {
        initComponents();
        jTableReportRevenue.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        Toolkit tk =Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();
        jLabel6.setSize(x, y);
    }
public void getUserName(String namestaff){
          name =namestaff;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReportRevenue = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReportRevenue = new javax.swing.JButton();
        jDChToRevenue = new com.toedter.calendar.JDateChooser();
        jDChFromRevenue = new com.toedter.calendar.JDateChooser();
        btnPrintReportRevenue = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRPRevenue = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("BÁO CÁO DOANH THU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 44, 332, 37);

        jTableReportRevenue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableReportRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReportRevenue);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 170, 780, 440);

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Báo cáo thống kê");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Từ ngày");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Đến ngày");

        btnReportRevenue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportRevenue.setForeground(new java.awt.Color(0, 0, 204));
        btnReportRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clipboard_edit.png"))); // NOI18N
        btnReportRevenue.setText("THỐNG KÊ");
        btnReportRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportRevenueActionPerformed(evt);
            }
        });

        jDChToRevenue.setDateFormatString("dd-MM-yyyy");
        jDChToRevenue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jDChFromRevenue.setDateFormatString("dd-MM-yyyy");
        jDChFromRevenue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnPrintReportRevenue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrintReportRevenue.setForeground(new java.awt.Color(0, 0, 204));
        btnPrintReportRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/print.png"))); // NOI18N
        btnPrintReportRevenue.setText("IN BÁO CÁO");
        btnPrintReportRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportRevenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDChFromRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(jDChToRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnReportRevenue)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrintReportRevenue)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDChFromRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDChToRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportRevenue)
                    .addComponent(btnPrintReportRevenue))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 144, 345, 238);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Top 10 doanh thu cao nhất của hóa đơn trong thời gian báo cáo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(393, 144, 443, 17);

        jScrollPane2.setOpaque(false);

        txaRPRevenue.setColumns(20);
        txaRPRevenue.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txaRPRevenue.setRows(5);
        jScrollPane2.setViewportView(txaRPRevenue);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(980, 200, 28, 36);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1180, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnReportRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportRevenueActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String FromDate, ToDate;
        if(jDChFromRevenue.getDate() == null)
            FromDate = "";
        else
            FromDate = df.format(jDChFromRevenue.getDate());
        if(jDChToRevenue.getDate() == null)
            ToDate = "";
        else
        ToDate = df.format(jDChToRevenue.getDate());
        control.bindingRPRevenue(jTableReportRevenue, billBLL.RPRevenue(FromDate, ToDate));
    }//GEN-LAST:event_btnReportRevenueActionPerformed

    private void btnPrintReportRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportRevenueActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String FromDate, ToDate;
        if(jDChFromRevenue.getDate() == null)
            FromDate = "";
        else
            FromDate = df.format(jDChFromRevenue.getDate());
        if(jDChToRevenue.getDate() == null)
            ToDate = "";
        else
        ToDate = df.format(jDChToRevenue.getDate());
        
        txaRPRevenue.setText("");
        txaRPRevenue.append("\t \t  NHÀ SÁCH TYQ \n \n");
        txaRPRevenue.append("Địa chỉ: Khu phố 6, P.Linh Trung, Q.Thủ Đức, TP.Hồ Chí Minh. \n" +
            "SĐT: 0962 111 222 \n" +
            "Email: nhasachTYQ@gmail.com \n \n");
        txaRPRevenue.append("\t \t BÁO CÁO DOANH THU \n");
        txaRPRevenue.append("\t \t (Từ ngày " + FromDate + " đến ngày " + ToDate + ") \n\n");
        txaRPRevenue.append("Tổng doanh số bán sách: " + billBLL.TotalRevenue(FromDate, ToDate) + "\n");
        txaRPRevenue.append("Tổng chi phí nhập sách: " + bookReceiptBLL.TotalExpense(FromDate, ToDate) + "\n");
        txaRPRevenue.append("Số lượng đơn hàng: " + billBLL.CountBill(FromDate, ToDate) + "\n\n");
        txaRPRevenue.append("Top 10 doanh số cao nhất của hóa đơn: \n");
        
        //SOHD, NGAYHD, MAKH, TENNV, TRIGIA, TONGTIEN    
        txaRPRevenue.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        txaRPRevenue.append("Số hóa đơn \tNgày hóa đơn    Mã khách hàng    Tên nhân viên \tTrị giá \t Tổng tiền \n");
        txaRPRevenue.append("--------------------------------------------------------------------------------------------------------------------------------\n");

        control.bindingRPRevenue(jTableReportRevenue, billBLL.RPRevenue(FromDate, ToDate));
        int row = jTableReportRevenue.getRowCount();
        int column = jTableReportRevenue.getColumnCount();
        for(int i=0; i < row; i++)
        {
            for(int j=0; j < column; j++)
            {
                txaRPRevenue.append(jTableReportRevenue.getValueAt(i, j).toString() + "\t");
                if(j == 1)
                    txaRPRevenue.append("\t");
            }
            txaRPRevenue.append("\n");
        }
        txaRPRevenue.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        txaRPRevenue.append("Ngày lập báo cáo: " + df.format(new Date()) + "\n");
        txaRPRevenue.append("Người lập báo cáo: "+ name) ;
        try {
            txaRPRevenue.print();
        } catch (PrinterException ex) {
            Logger.getLogger(fReportRevenue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintReportRevenueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintReportRevenue;
    private javax.swing.JButton btnReportRevenue;
    private com.toedter.calendar.JDateChooser jDChFromRevenue;
    private com.toedter.calendar.JDateChooser jDChToRevenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableReportRevenue;
    private javax.swing.JTextArea txaRPRevenue;
    // End of variables declaration//GEN-END:variables
}
