/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CustomerBLL;
import Utilties.ControlFormat;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form fCustomer
     */
    int flag = 0;
    ControlFormat control = new ControlFormat();
    CustomerBLL customerBLL = new CustomerBLL();
     Date Today = new java.util.Date();
    
    public fCustomer() {
        initComponents();
        Toolkit tk =Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();
        setSize(x, y);
        control.BindingCustomer(jTableCustomer, customerBLL.LoadCustomer());
        jDChRegisDateCustomer.setDate(Today);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfSearchCustomer = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txfIDCustomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfNameCustomer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfAddressCustomer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfPhoneCustomer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDChBirthdayCustomer = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jDChRegisDateCustomer = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txfTurnoverCustomer = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        btnEditCustomer = new javax.swing.JButton();
        btnSaveCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(276, 27, 350, 37);

        txfSearchCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txfSearchCustomer);
        txfSearchCustomer.setBounds(10, 91, 275, 25);

        btnSearchCustomer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSearchCustomer.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchCustomer.setText("Tìm kiếm");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchCustomer);
        btnSearchCustomer.setBounds(314, 90, 120, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Mã khách hàng:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 151, 110, 17);

        txfIDCustomer.setEditable(false);
        txfIDCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txfIDCustomer);
        txfIDCustomer.setBounds(140, 151, 260, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Tên khách hàng:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 201, 120, 19);

        txfNameCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfNameCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNameCustomerActionPerformed(evt);
            }
        });
        txfNameCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfNameCustomerKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfNameCustomerKeyTyped(evt);
            }
        });
        getContentPane().add(txfNameCustomer);
        txfNameCustomer.setBounds(140, 201, 260, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Địa chỉ:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 241, 106, 19);

        txfAddressCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txfAddressCustomer);
        txfAddressCustomer.setBounds(140, 244, 260, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Số điện thoại:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 281, 106, 19);

        txfPhoneCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfPhoneCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfPhoneCustomerKeyTyped(evt);
            }
        });
        getContentPane().add(txfPhoneCustomer);
        txfPhoneCustomer.setBounds(140, 281, 260, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Ngày sinh:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 331, 79, 19);

        jDChBirthdayCustomer.setDateFormatString("dd-MM-yyyy");
        jDChBirthdayCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(jDChBirthdayCustomer);
        jDChBirthdayCustomer.setBounds(140, 321, 260, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Ngày đăng kí:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 371, 106, 26);

        jDChRegisDateCustomer.setDateFormatString("dd-MM-yyyy");
        jDChRegisDateCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(jDChRegisDateCustomer);
        jDChRegisDateCustomer.setBounds(140, 371, 260, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Doanh số:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 419, 73, 19);

        txfTurnoverCustomer.setEditable(false);
        txfTurnoverCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txfTurnoverCustomer);
        txfTurnoverCustomer.setBounds(140, 419, 260, 25);

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(0, 0, 204));
        btnAddCustomer.setText("THÊM");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCustomer);
        btnAddCustomer.setBounds(39, 500, 110, 27);

        btnEditCustomer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnEditCustomer.setForeground(new java.awt.Color(0, 0, 204));
        btnEditCustomer.setText("CẬP NHẬT");
        btnEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditCustomer);
        btnEditCustomer.setBounds(190, 500, 130, 27);

        btnSaveCustomer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSaveCustomer.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveCustomer.setText("LƯU");
        btnSaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveCustomer);
        btnSaveCustomer.setBounds(360, 500, 120, 27);

        jTableCustomer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại", "Ngày sinh", "Ngày đăng kí", "Doanh số"
            }
        ));
        jTableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCustomer);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 90, 800, 580);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1360, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ClearTextCustomer()
    {
        txfIDCustomer.setText("");
        txfNameCustomer.setText("");
        txfAddressCustomer.setText("");
        txfPhoneCustomer.setText("");
        jDChBirthdayCustomer.setDate(null);
        jDChRegisDateCustomer.setDate(Today);
    }
    //Hàm chuẩn hóa tên
    public String chuanHoa(String str) {
        str = str.trim();
        str = str.replaceAll("\\s+", " ");
        return str;
    }
 
    public String chuanHoaDanhTuRieng(String str) {
        str = chuanHoa(str.toLowerCase());
        String temp[] = str.split(" ");
        str = ""; // ? ^-^
        for (int i = 0; i < temp.length; i++) {
            str += String.valueOf(temp[i].charAt(0)).toUpperCase() + temp[i].substring(1);
            if (i < temp.length - 1) // ? ^-^
                str += " ";
        }
        return str;
    } 
    //Thêm khách hàng
    public boolean InsertCustomer()
    {        
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        
        String NameCustomer = txfNameCustomer.getText();
        String AddressCustomer = txfAddressCustomer.getText();
        String PhoneCustomer = txfPhoneCustomer.getText();

        String strBirthdayCustomer = formatter.format(jDChBirthdayCustomer.getDate());
        String strRegisDateCustomer = formatter.format(jDChRegisDateCustomer.getDate());
        
        if(NameCustomer.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên khách hàng bắt buộc phải có");
            return false;
        }
        else if(AddressCustomer.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Địa chỉ khách hàng bắt buộc phải có");
            return false;
        }
            
        else
        {
            fCustomer f = new fCustomer();
            NameCustomer = f.chuanHoaDanhTuRieng(NameCustomer);
        
            if(customerBLL.InsertCustomer(NameCustomer, AddressCustomer, PhoneCustomer, strBirthdayCustomer, strRegisDateCustomer))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công khách hàng");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại khách hàng!");
                return false;
            }
            
        }
    }
    
    //Cập nhật khách hàng
    public boolean UpdateCustomer()
    {        
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        
        int IDCustomer = Integer.parseInt(txfIDCustomer.getText());
        String NameCustomer = txfNameCustomer.getText();
        String AddressCustomer = txfAddressCustomer.getText();
        String PhoneCustomer = txfPhoneCustomer.getText();

        String strBirthdayCustomer = formatter.format(jDChBirthdayCustomer.getDate());
        String strRegisDateCustomer = formatter.format(jDChRegisDateCustomer.getDate());
        
        if(NameCustomer.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên khách hàng bắt buộc phải có");
            return false;
        }
        else if(AddressCustomer.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Địa chỉ khách hàng bắt buộc phải có");
            return false;
        }
            
        else
        {
            fCustomer f = new fCustomer();
            NameCustomer = f.chuanHoaDanhTuRieng(NameCustomer);
        
            if(customerBLL.UpdateCustomer(IDCustomer, NameCustomer, AddressCustomer, PhoneCustomer, strBirthdayCustomer, strRegisDateCustomer))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công khách hàng");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại khách hàng!");
                return false;
            }
            
        }
    }
    
    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        // TODO add your handling code here:
        String key = txfSearchCustomer.getText();
        control.BindingCustomer(jTableCustomer, customerBLL.SearchCustomer(key));
        txfSearchCustomer.setText("");
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void txfNameCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNameCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNameCustomerActionPerformed

    private void txfNameCustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNameCustomerKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txfNameCustomerKeyPressed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        ClearTextCustomer();
        btnAddCustomer.setEnabled(false);
        btnEditCustomer.setEnabled(false);
        btnSaveCustomer.setEnabled(true);
        flag = 4;
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerActionPerformed
        // TODO add your handling code here:
        btnAddCustomer.setEnabled(false);
        btnEditCustomer.setEnabled(false);
        btnSaveCustomer.setEnabled(true);
        flag=2;
    }//GEN-LAST:event_btnEditCustomerActionPerformed

    private void btnSaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCustomerActionPerformed
        // TODO add your handling code here:
        if(flag==4)
        {
            if(InsertCustomer() == true)
            {
                btnAddCustomer.setEnabled(true);
                btnEditCustomer.setEnabled(true);
                btnSaveCustomer.setEnabled(false);
                control.BindingCustomer(jTableCustomer, customerBLL.LoadCustomer());
                ClearTextCustomer();
            }
        }

        if(flag==2)
        {
            if(UpdateCustomer() == true)
            {
                btnAddCustomer.setEnabled(true);
                btnEditCustomer.setEnabled(true);
                btnSaveCustomer.setEnabled(false);
                control.BindingCustomer(jTableCustomer, customerBLL.LoadCustomer());
                ClearTextCustomer();
            }
        }
    }//GEN-LAST:event_btnSaveCustomerActionPerformed

    private void jTableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerMouseClicked
        // TODO add your handling code here:
        int row = jTableCustomer.getSelectedRow();
        txfIDCustomer.setText(jTableCustomer.getValueAt(row, 0).toString());
        txfNameCustomer.setText(jTableCustomer.getValueAt(row, 1).toString());
        txfAddressCustomer.setText(jTableCustomer.getValueAt(row, 2).toString());
        txfPhoneCustomer.setText(jTableCustomer.getValueAt(row, 3).toString());
        jDChBirthdayCustomer.setDate((Date) jTableCustomer.getModel().getValueAt(row, 4));
        jDChRegisDateCustomer.setDate((Date) jTableCustomer.getModel().getValueAt(row, 5));
        txfTurnoverCustomer.setText(jTableCustomer.getValueAt(row, 6).toString());
    }//GEN-LAST:event_jTableCustomerMouseClicked

    private void txfNameCustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNameCustomerKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNameCustomerKeyTyped

    private void txfPhoneCustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfPhoneCustomerKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) || txfPhoneCustomer.getText().length() >= 10)
            evt.consume();
    }//GEN-LAST:event_txfPhoneCustomerKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnSaveCustomer;
    private javax.swing.JButton btnSearchCustomer;
    private com.toedter.calendar.JDateChooser jDChBirthdayCustomer;
    private com.toedter.calendar.JDateChooser jDChRegisDateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JTextField txfAddressCustomer;
    private javax.swing.JTextField txfIDCustomer;
    private javax.swing.JTextField txfNameCustomer;
    private javax.swing.JTextField txfPhoneCustomer;
    private javax.swing.JTextField txfSearchCustomer;
    private javax.swing.JTextField txfTurnoverCustomer;
    // End of variables declaration//GEN-END:variables
}
