/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.BookBLL;
import  Entity.Distributor;
import DAL.DistributorDAL;
import  Utilties.ControlFormat;
import BLL.DistributorBLL;
import BLL.BookReceiptBLL;
import BLL.BookReceiptInfoBLL;
import Entity.Book;
import Entity.BookReceipt;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author STIREN
 */
public class fImportBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form f
     */
    private int flag=0;
    ControlFormat control =new ControlFormat();
    DistributorBLL distributorBLL=new DistributorBLL();
    BookReceiptBLL bookReceiptBLL=new BookReceiptBLL();
    BookBLL bookbll =new BookBLL();
    BookReceiptInfoBLL bookReceiptInfoBLL =new BookReceiptInfoBLL();
    public fImportBook() {
        initComponents();
        Toolkit tk =Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();
        jPanel1.setSize(x, y);
        jPanel3.setSize(x, y);
        jLabel6.setSize((int)jPanel1.getSize().getWidth(), (int)jPanel1.getSize().getHeight());
        control.bindingDistributor(jTableDistributorInfo,distributorBLL.LoadDistributor());
        control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
        control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.LoadBookReceiptInfo());
        control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
        Date date =new Date();
        jDateChooserReceipt.setDate(date);
        cbNameDistributorReceipt.removeAllItems();
        for(Distributor distributor: distributorBLL.LoadDistributor())
        {
            cbNameDistributorReceipt.addItem(distributor.getNameDistributor());
        }
       
        
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txfSearchDistributor = new javax.swing.JTextField();
        btnSearchDistributorReceipt = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfIDDistributorInfo = new javax.swing.JTextField();
        txfNameDistributorInfo = new javax.swing.JTextField();
        txfAddressDistributorInfo = new javax.swing.JTextField();
        txfPhoneDistributorInfo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAddDistributorInfo = new javax.swing.JButton();
        btnEditDistributorInfo = new javax.swing.JButton();
        btnSaveDistributorInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDistributorInfo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnSaveReceiptInfo = new javax.swing.JButton();
        btnDelReceiptInfo = new javax.swing.JButton();
        btnEditReceiptInfo = new javax.swing.JButton();
        btnAddReceiptInfo = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txfAmountReceiptInfo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txfAmount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txfCost = new javax.swing.JTextField();
        txfNameBook = new javax.swing.JTextField();
        txfIDReceiptInfo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReceiptInfo = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        txfSearchStockInfo = new javax.swing.JTextField();
        btnSearchReceiptInfo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfIDReceipt = new javax.swing.JTextField();
        jDateChooserReceipt = new com.toedter.calendar.JDateChooser();
        cbNameDistributorReceipt = new javax.swing.JComboBox<>();
        txfTotalReceipt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnAddReceipt = new javax.swing.JButton();
        btnEditReceipt = new javax.swing.JButton();
        btnSaveReceipt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReceipt = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableBook = new javax.swing.JTable();
        txfSearchBook = new javax.swing.JTextField();
        btnSearchBook = new javax.swing.JButton();
        txfSearchReceipt1 = new javax.swing.JTextField();
        btnSearchReceipt1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("QUẢN LÝ NHẬP SÁCH");

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÍ THÔNG TIN NHÀ CUNG CẤP SÁCH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(159, 53, 647, 37);

        jPanel4.setOpaque(false);

        txfSearchDistributor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchDistributorReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchDistributorReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchDistributorReceipt.setText("Tìm kiếm");
        btnSearchDistributorReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDistributorReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfSearchDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnSearchDistributorReceipt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchDistributorReceipt)
                    .addComponent(txfSearchDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 101, 387, 66);

        jPanel5.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Mã nhà cung cấp");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Tên nhà cung cấp");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Số điện thoại");

        txfIDDistributorInfo.setEditable(false);
        txfIDDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfNameDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfAddressDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfPhoneDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfPhoneDistributorInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfPhoneDistributorInfoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfIDDistributorInfo)
                    .addComponent(txfNameDistributorInfo)
                    .addComponent(txfAddressDistributorInfo)
                    .addComponent(txfPhoneDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfIDDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfNameDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfAddressDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfPhoneDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 193, 510, 240);

        jPanel6.setOpaque(false);

        btnAddDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddDistributorInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnAddDistributorInfo.setText("THÊM");
        btnAddDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDistributorInfoActionPerformed(evt);
            }
        });

        btnEditDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditDistributorInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnEditDistributorInfo.setText("CẬP NHẬT");
        btnEditDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDistributorInfoActionPerformed(evt);
            }
        });

        btnSaveDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveDistributorInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveDistributorInfo.setText("LƯU");
        btnSaveDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDistributorInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDistributorInfo)
                .addGap(42, 42, 42)
                .addComponent(btnEditDistributorInfo)
                .addGap(61, 61, 61)
                .addComponent(btnSaveDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDistributorInfo)
                    .addComponent(btnEditDistributorInfo)
                    .addComponent(btnSaveDistributorInfo))
                .addContainerGap())
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(39, 447, 399, 47);

        jTableDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableDistributorInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại", "Email"
            }
        ));
        jTableDistributorInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDistributorInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDistributorInfo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(510, 120, 830, 590);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1460, 720);

        jTabbedPane1.addTab("Nhà cung cấp sách", jPanel1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("QUẢN LÍ CHI TIẾT PHIẾU NHẬP SÁCH");

        jPanel10.setOpaque(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.setOpaque(false);

        btnSaveReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveReceiptInfo.setText("LƯU");
        btnSaveReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveReceiptInfoActionPerformed(evt);
            }
        });

        btnDelReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnDelReceiptInfo.setText("XÓA");
        btnDelReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelReceiptInfoActionPerformed(evt);
            }
        });

        btnEditReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnEditReceiptInfo.setText("CẬP NHẬT");
        btnEditReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditReceiptInfoActionPerformed(evt);
            }
        });

        btnAddReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnAddReceiptInfo.setText("THÊM");
        btnAddReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReceiptInfoActionPerformed(evt);
            }
        });

        jPanel11.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Số phiếu nhập");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Tên sách");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Số lượng");

        txfAmountReceiptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfAmountReceiptInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfAmountReceiptInfoKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Thành tiền");

        txfAmount.setEditable(false);
        txfAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Giá nhập");

        txfCost.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfCostKeyTyped(evt);
            }
        });

        txfNameBook.setEditable(false);
        txfNameBook.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfIDReceiptInfo.setEditable(false);
        txfIDReceiptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfCost, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(txfAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfAmountReceiptInfo)
                    .addComponent(txfNameBook)
                    .addComponent(txfIDReceiptInfo))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txfIDReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(txfNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16))
                    .addComponent(txfAmountReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txfCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnAddReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditReceiptInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveReceiptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddReceiptInfo)
                    .addComponent(btnEditReceiptInfo)
                    .addComponent(btnDelReceiptInfo)
                    .addComponent(btnSaveReceiptInfo))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jTableReceiptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableReceiptInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số phiếu nhập", "Mã sách", "Số lượng", "Thành tiền"
            }
        ));
        jTableReceiptInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceiptInfoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableReceiptInfo);

        jPanel13.setOpaque(false);

        txfSearchStockInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfSearchStockInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSearchStockInfoActionPerformed(evt);
            }
        });

        btnSearchReceiptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchReceiptInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchReceiptInfo.setText("Tìm kiếm");
        btnSearchReceiptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReceiptInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(txfSearchStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSearchReceiptInfo)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearchStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchReceiptInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Ngày nhập");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Tổng tiền");

        txfIDReceipt.setEditable(false);
        txfIDReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jDateChooserReceipt.setDateFormatString("dd-MM-yyyy");
        jDateChooserReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cbNameDistributorReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfTotalReceipt.setEditable(false);
        txfTotalReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Tên nhà cung cấp");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Số phiếu nhập");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(cbNameDistributorReceipt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfIDReceipt)
                            .addComponent(txfTotalReceipt)))
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfIDReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(jDateChooserReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNameDistributorReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txfTotalReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel9.setOpaque(false);

        btnAddReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnAddReceipt.setText("THÊM");
        btnAddReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReceiptActionPerformed(evt);
            }
        });

        btnEditReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnEditReceipt.setText("CẬP NHẬT");
        btnEditReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditReceiptActionPerformed(evt);
            }
        });

        btnSaveReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveReceipt.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveReceipt.setText("LƯU");
        btnSaveReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(btnAddReceipt)
                .addGap(35, 35, 35)
                .addComponent(btnEditReceipt)
                .addGap(28, 28, 28)
                .addComponent(btnSaveReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddReceipt)
                    .addComponent(btnEditReceipt)
                    .addComponent(btnSaveReceipt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số phiếu nhập", "Ngày nhập", "Mã nhà cung cấp", "Tên nhà cung cấp", "Tổng tiền"
            }
        ));
        jTableReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceiptMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableReceipt);

        jTableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBookMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableBook);

        txfSearchBook.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSearchBookActionPerformed(evt);
            }
        });

        btnSearchBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchBook.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchBook.setText("Tìm kiếm");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });

        txfSearchReceipt1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchReceipt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchReceipt1.setForeground(new java.awt.Color(0, 0, 204));
        btnSearchReceipt1.setText("Tìm kiếm");
        btnSearchReceipt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReceipt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txfSearchReceipt1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchReceipt1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txfSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnSearchBook))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfSearchReceipt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchReceipt1)
                                    .addComponent(txfSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchBook))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(264, 264, 264))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(208, 208, 208))))
        );

        jTabbedPane1.addTab("Chi tiết phiếu nhập sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDistributorInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDistributorInfoMouseClicked
        // TODO add your handling code here:
        int row=jTableDistributorInfo.getSelectedRow();
        txfIDDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 0).toString());
        txfNameDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 1).toString());
        txfAddressDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 2).toString());
        txfPhoneDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTableDistributorInfoMouseClicked

    private void btnSaveDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDistributorInfoActionPerformed
        // TODO add your handling code here:
        if(flag==1)
        {
            if(InsertDistributor()==true)
            {
                control.bindingDistributor(jTableDistributorInfo, distributorBLL.LoadDistributor());
            }
            btnAddDistributorInfo.setEnabled(true);
            btnEditDistributorInfo.setEnabled(true);
            btnSaveDistributorInfo.setEnabled(false);
        }
        if(flag==2)
        {
            if(UpdateDistributor()==true)
            {
                control.bindingDistributor(jTableDistributorInfo, distributorBLL.LoadDistributor());
            }
            btnAddDistributorInfo.setEnabled(true);
            btnEditDistributorInfo.setEnabled(true);
            btnSaveDistributorInfo.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveDistributorInfoActionPerformed

    private void btnEditDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDistributorInfoActionPerformed
        // TODO add your handling code here:
        btnAddDistributorInfo.setEnabled(false);
        btnEditDistributorInfo.setEnabled(false);
        btnSaveDistributorInfo.setEnabled(true);
        flag=2;
    }//GEN-LAST:event_btnEditDistributorInfoActionPerformed

    private void btnAddDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDistributorInfoActionPerformed
        // TODO add your handling code here:
        ClearTextDistibutor();
        btnAddDistributorInfo.setEnabled(false);
        btnEditDistributorInfo.setEnabled(false);
        btnSaveDistributorInfo.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddDistributorInfoActionPerformed

    private void txfPhoneDistributorInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfPhoneDistributorInfoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) || txfPhoneDistributorInfo.getText().length() >= 10)
        evt.consume();
    }//GEN-LAST:event_txfPhoneDistributorInfoKeyTyped

    private void btnSearchDistributorReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDistributorReceiptActionPerformed
        // TODO add your handling code here:
        String key=txfSearchDistributor.getText();
        control.bindingDistributor(jTableDistributorInfo, distributorBLL.SearchDistributor(key));
        txfSearchDistributor.setText("");
    }//GEN-LAST:event_btnSearchDistributorReceiptActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        // TODO add your handling code here:
        String key =txfSearchBook.getText();
        control.bindingBook(jTableBook, bookbll.SearchBook(key));
        txfSearchBook.setText("");
        if(jTableBook.getRowCount()==0)
        {
            fListBook f =new fListBook();
            int x = (int) tk.getScreenSize().getWidth();
            int y = (int) tk.getScreenSize().getHeight();
            f.setSize(x, y);
            jTabbedPane1.add(f);
            f.setVisible(true);
            control.bindingBook(jTableBook, bookbll.LoadBook());

        }
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void jTableBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBookMouseClicked
        // TODO add your handling code here:
        int row=jTableBook.getSelectedRow();
        txfNameBook.setText(jTableBook.getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTableBookMouseClicked

    private void jTableReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceiptMouseClicked
        // TODO add your handling code here:
        int row=jTableReceipt.getSelectedRow();
        txfIDReceipt.setText(jTableReceipt.getValueAt(row, 0).toString());
        int IDBooReceipt=Integer.parseInt(txfIDReceipt.getText().toString());
        txfIDReceiptInfo.setText(jTableReceipt.getValueAt(row, 0).toString());
        jDateChooserReceipt.setDate((Date)jTableReceipt.getModel().getValueAt(row, 1));
        String NameDistributor =jTableReceipt.getValueAt(row, 2).toString();
        if(jTableReceipt.getValueAt(row, 2).toString().equals(NameDistributor))
        cbNameDistributorReceipt.setSelectedItem(NameDistributor);
        txfTotalReceipt.setText(jTableReceipt.getValueAt(row, 3).toString());
        control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.SearchBookReceiptInfo(IDBooReceipt));
    }//GEN-LAST:event_jTableReceiptMouseClicked

    private void btnSearchReceipt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchReceipt1ActionPerformed
        // TODO add your handling code here:
        String key =txfSearchReceipt1.getText().toString();
        control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.SearchBookReceipt(key));
        txfSearchReceipt1.setText("");
    }//GEN-LAST:event_btnSearchReceipt1ActionPerformed

    private void btnSaveReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveReceiptActionPerformed
        // TODO add your handling code here:
        if(flag==4)
        {
            if(InsertBookReceipt()==true)
            {
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());

            }
            btnAddReceipt.setEnabled(true);
            btnEditReceipt.setEnabled(true);
            btnSaveReceipt.setEnabled(false);
        }
        if(flag==5)
        {
            if(UpdateBookReceipt()==true)
            {
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
            }
            btnAddReceipt.setEnabled(true);
            btnEditReceipt.setEnabled(true);
            btnSaveReceipt.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveReceiptActionPerformed

    private void btnEditReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditReceiptActionPerformed
        // TODO add your handling code here:
        btnAddReceipt.setEnabled(false);
        btnEditReceipt.setEnabled(false);
        btnSaveReceipt.setEnabled(true);
        flag=5;
    }//GEN-LAST:event_btnEditReceiptActionPerformed

    private void btnAddReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReceiptActionPerformed
        // TODO add your handling code here:
        ClearTextBookReceipt();
        txfIDReceiptInfo.setText(String.valueOf(txfIDReceipt.getText()));
        btnAddReceipt.setEnabled(false);
        btnEditReceipt.setEnabled(false);
        btnSaveReceipt.setEnabled(true);
        flag=4;
    }//GEN-LAST:event_btnAddReceiptActionPerformed

    private void btnSearchReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchReceiptInfoActionPerformed
        // TODO add your handling code here:
        int key =Integer.parseInt(txfSearchStockInfo.getText().toString());
        control.bindingBookReceiptInfo(jTableReceiptInfo,bookReceiptInfoBLL.SearchBookReceiptInfo(key));
        txfSearchStockInfo.setText("");
    }//GEN-LAST:event_btnSearchReceiptInfoActionPerformed

    private void txfSearchStockInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSearchStockInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSearchStockInfoActionPerformed

    private void jTableReceiptInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceiptInfoMouseClicked
        // TODO add your handling code here:
        int row=jTableReceiptInfo.getSelectedRow();

        txfIDReceiptInfo.setText(jTableReceiptInfo.getValueAt(row, 0).toString());
        txfNameBook.setText(jTableReceiptInfo.getValueAt(row, 1).toString());
        txfAmountReceiptInfo.setText(jTableReceiptInfo.getValueAt(row, 2).toString());
        txfCost.setText(jTableReceiptInfo.getValueAt(row, 3).toString());
        txfAmount.setText(jTableReceiptInfo.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTableReceiptInfoMouseClicked

    private void txfCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfCostKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (txfCost.getText().equals(""))
        dot = false;
        if (dot == false){
            if (vChar == '.')
            dot = true;
            else if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
        else {
            if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
    }//GEN-LAST:event_txfCostKeyTyped

    private void txfAmountReceiptInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfAmountReceiptInfoKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar();
        if (txfAmountReceiptInfo.getText().equals(""))
        dot = false;
        if (dot == false){
            if (vChar == '.')
            dot = true;
            else if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
        else {
            if (!(Character.isDigit(vChar)|| (vChar == KeyEvent.VK_BACK_SPACE)|| (vChar == KeyEvent.VK_DELETE)))
            evt.consume();
        }
    }//GEN-LAST:event_txfAmountReceiptInfoKeyTyped

    private void btnAddReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReceiptInfoActionPerformed
        // TODO add your handling code here:
        ClearTextReceiptInfo();
        txfIDReceiptInfo.setText(String.valueOf(txfIDReceipt.getText()));
        btnAddReceiptInfo.setEnabled(false);
        btnEditReceiptInfo.setEnabled(false);
        btnDelReceiptInfo.setEnabled(false);
        btnSaveReceiptInfo.setEnabled(true);
        flag=7;
    }//GEN-LAST:event_btnAddReceiptInfoActionPerformed

    private void btnEditReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditReceiptInfoActionPerformed
        // TODO add your handling code here:
        btnAddReceiptInfo.setEnabled(false);
        btnEditReceiptInfo.setEnabled(false);
        btnDelReceiptInfo.setEnabled(false);
        btnSaveReceiptInfo.setEnabled(true);
        flag=8;
    }//GEN-LAST:event_btnEditReceiptInfoActionPerformed

    private void btnDelReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelReceiptInfoActionPerformed
        // TODO add your handling code here:
        btnAddReceiptInfo.setEnabled(false);
        btnEditReceiptInfo.setEnabled(false);
        btnDelReceiptInfo.setEnabled(false);
        btnSaveReceiptInfo.setEnabled(true);
        flag=9;
    }//GEN-LAST:event_btnDelReceiptInfoActionPerformed

    private void btnSaveReceiptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveReceiptInfoActionPerformed
        // TODO add your handling code here:
        if(flag==7)
        {
            if(InsertBookReceiptInfo()==true)
            {
                control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.LoadBookReceiptInfo());
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
                int IDReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                txfTotalReceipt.setText(String.valueOf(bookReceiptBLL.getTotalReceipt(IDReceipt)));
                txfNameDistributorInfo.setText(bookReceiptBLL.getDistributor(IDReceipt));
                jDateChooserReceipt.setDate(bookReceiptBLL.getDateReceipt(IDReceipt));
            }
            btnAddReceiptInfo.setEnabled(true);
            btnEditReceiptInfo.setEnabled(true);
            btnDelReceiptInfo.setEnabled(true);
            btnSaveReceiptInfo.setEnabled(false);
        }
        if(flag==8)
        {
            if(UpdateBookReceiptInfo()==true)
            {
                control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.LoadBookReceiptInfo());
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
                int IDReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                txfTotalReceipt.setText(String.valueOf(bookReceiptBLL.getTotalReceipt(IDReceipt)));
                txfNameDistributorInfo.setText(bookReceiptBLL.getDistributor(IDReceipt));
                jDateChooserReceipt.setDate(bookReceiptBLL.getDateReceipt(IDReceipt));
            }
            btnAddReceiptInfo.setEnabled(true);
            btnEditReceiptInfo.setEnabled(true);
            btnDelReceiptInfo.setEnabled(true);
            btnSaveReceiptInfo.setEnabled(false);
        }
        if(flag==9)
        {
            if(DeleteBookReceiptInfo()==true)
            {
                control.bindingBookReceiptInfo(jTableReceiptInfo, bookReceiptInfoBLL.LoadBookReceiptInfo());
                control.bindingBookReceipt(jTableReceipt, bookReceiptBLL.LoadBookReceipt());
                control.bindingIDNameBook(jTableBook, bookbll.LoadidNameBook());
                int IDReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
                txfTotalReceipt.setText(String.valueOf(bookReceiptBLL.getTotalReceipt(IDReceipt)));
                txfNameDistributorInfo.setText(bookReceiptBLL.getDistributor(IDReceipt));
                jDateChooserReceipt.setDate(bookReceiptBLL.getDateReceipt(IDReceipt));
            }
            btnAddReceiptInfo.setEnabled(true);
            btnEditReceiptInfo.setEnabled(true);
            btnDelReceiptInfo.setEnabled(true);
            btnSaveReceiptInfo.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveReceiptInfoActionPerformed

    private void txfSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSearchBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSearchBookActionPerformed
    public String chuanHoa(String str) {
        str = str.trim();
        str = str.replaceAll("\\s+", " ");
        return str;
    }
    public void ClearTextReceiptInfo()
    {
        
        txfAmountReceiptInfo.setText("");
        txfCost.setText("");
        txfAmount.setText("");
    }    Toolkit tk = Toolkit.getDefaultToolkit();    boolean dot = false;    public void ClearTextDistibutor()
    {
        txfIDDistributorInfo.setText("");
        txfNameDistributorInfo.setText("");
        txfAddressDistributorInfo.setText("");
        txfPhoneDistributorInfo.setText("");
    }
    public boolean InsertDistributor()
    {
        String NameDistributor =txfNameDistributorInfo.getText().toString();
        String Address =txfAddressDistributorInfo.getText().toString();
        String PhoneNumber =txfPhoneDistributorInfo.getText().toString();
        if(txfNameDistributorInfo.getText().toString().equals("")|| txfPhoneDistributorInfo.getText().toString().equals("") || txfAddressDistributorInfo.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, địa chỉ, số điện thoại là bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            Address=chuanHoa(Address);
            if(distributorBLL.InsertDistributor(NameDistributor, Address, PhoneNumber))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công nhà cung cấp");
                return true;
            }   
                else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
        }
        
    }
    public boolean UpdateDistributor()
    {
        int IDDistributor=Integer.parseInt(txfIDDistributorInfo.getText().toString());
        String NameDistributor =txfNameDistributorInfo.getText().toString();
        String Address =txfAddressDistributorInfo.getText().toString();
        String PhoneNumber =txfPhoneDistributorInfo.getText().toString();
        if(txfNameDistributorInfo.getText().toString().equals("")|| txfPhoneDistributorInfo.getText().toString().equals("") || txfAddressDistributorInfo.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, địa chỉ, số điện thoại là bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            Address=chuanHoa(Address);
            if(distributorBLL.UpdateDistributor(IDDistributor,NameDistributor, Address, PhoneNumber))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công nhà cung cấp");
                return true;
            }   
                else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
        }
    }
      public void ClearTextBookReceipt()
    {
        txfIDReceipt.setText("");
        txfTotalReceipt.setText("");
    }
    public boolean InsertBookReceipt()
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date DateReceipt=jDateChooserReceipt.getDate();
        String strDateReceipt = formatter.format(DateReceipt);
        String NameDistributor =cbNameDistributorReceipt.getSelectedItem().toString();
        int IDDistributor=distributorBLL.getIDDistributor(NameDistributor);
        if(NameDistributor.equals("") || strDateReceipt.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, ngày nhập, thành tiền là các trường bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            
            if(bookReceiptBLL.InsertBookReceipt(strDateReceipt, IDDistributor))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
            
        }
        
        
    }
    public boolean  UpdateBookReceipt()
    {
        int IDBookReceipt =Integer.parseInt(txfIDReceipt.getText().toString());
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date DateReceipt=jDateChooserReceipt.getDate();
        String strDateReceipt = formatter.format(DateReceipt);
        String NameDistributor =cbNameDistributorReceipt.getSelectedItem().toString();
        int IDDistributor=distributorBLL.getIDDistributor(NameDistributor);
        float TotalReceipt=Float.parseFloat(txfTotalReceipt.getText().toString());
        if(NameDistributor.equals("") || strDateReceipt.equals("")|| txfTotalReceipt.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, ngày nhập, thành tiền là các trường bắt buộc");
            return false;
        }
        else
        {
            NameDistributor=chuanHoa(NameDistributor);
            if(bookReceiptBLL.UpdateBookReceipt(IDBookReceipt, strDateReceipt, IDDistributor))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
            
        }
        
    }
   
    public boolean InsertBookReceiptInfo()
    {
        int IDBookReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
        int row =jTableBook.getSelectedRow();
        String NameBook=jTableBook.getValueAt(row, 1).toString();
        int IDBook=bookbll.getIDBook(NameBook);
        int AmountReceipt=Integer.parseInt(txfAmountReceiptInfo.getText().toString());
        float Cost =Float.parseFloat(txfCost.getText().toString());
        if(String.valueOf(IDBookReceipt).equals("")|| NameBook.equals("") ||txfAmountReceiptInfo.equals("")|| txfCost.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nhập thông tin chưa đầy đủ");
            return false;
        }
       else
        {
            if(bookReceiptInfoBLL.InsertBookReceiptInfo(IDBookReceipt, IDBook, AmountReceipt,Cost))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
        }
    }
    public boolean  UpdateBookReceiptInfo()
    {
        int IDBookReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
        int row =jTableBook.getSelectedRow();
        String NameBook=jTableBook.getValueAt(row, 1).toString();
        int IDBook=bookbll.getIDBook(NameBook);
        int AmountReceipt=Integer.parseInt(txfAmountReceiptInfo.getText());
        float Cost=Float.parseFloat(txfCost.getText());
        if(String.valueOf(IDBookReceipt).equals("")|| NameBook.equals("")||txfAmountReceiptInfo.equals("")|| txfCost.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nhập thông tin chưa đầy đủ");
            return false;
        }
       else
        {
            if(bookReceiptInfoBLL.UpdateBookReceiptInfo(IDBookReceipt, IDBook, AmountReceipt,Cost))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
        }
     
    }
    public boolean DeleteBookReceiptInfo()
    {
       int IDBookReceipt=Integer.parseInt(txfIDReceiptInfo.getText().toString());
       String NameBook="";//=cbNameBookReceiptInfo.getSelectedItem().toString();
       int IDBook =bookbll.getIDBook(NameBook);
       if(bookReceiptInfoBLL.DeleteBookReceiptInfo(IDBookReceipt,IDBook))
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
                return false;
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDistributorInfo;
    private javax.swing.JButton btnAddReceipt;
    private javax.swing.JButton btnAddReceiptInfo;
    private javax.swing.JButton btnDelReceiptInfo;
    private javax.swing.JButton btnEditDistributorInfo;
    private javax.swing.JButton btnEditReceipt;
    private javax.swing.JButton btnEditReceiptInfo;
    private javax.swing.JButton btnSaveDistributorInfo;
    private javax.swing.JButton btnSaveReceipt;
    private javax.swing.JButton btnSaveReceiptInfo;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnSearchDistributorReceipt;
    private javax.swing.JButton btnSearchReceipt1;
    private javax.swing.JButton btnSearchReceiptInfo;
    private javax.swing.JComboBox<String> cbNameDistributorReceipt;
    private com.toedter.calendar.JDateChooser jDateChooserReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBook;
    private javax.swing.JTable jTableDistributorInfo;
    private javax.swing.JTable jTableReceipt;
    private javax.swing.JTable jTableReceiptInfo;
    private javax.swing.JTextField txfAddressDistributorInfo;
    private javax.swing.JTextField txfAmount;
    private javax.swing.JTextField txfAmountReceiptInfo;
    private javax.swing.JTextField txfCost;
    private javax.swing.JTextField txfIDDistributorInfo;
    private javax.swing.JTextField txfIDReceipt;
    private javax.swing.JTextField txfIDReceiptInfo;
    private javax.swing.JTextField txfNameBook;
    private javax.swing.JTextField txfNameDistributorInfo;
    private javax.swing.JTextField txfPhoneDistributorInfo;
    private javax.swing.JTextField txfSearchBook;
    private javax.swing.JTextField txfSearchDistributor;
    private javax.swing.JTextField txfSearchReceipt1;
    private javax.swing.JTextField txfSearchStockInfo;
    private javax.swing.JTextField txfTotalReceipt;
    // End of variables declaration//GEN-END:variables
}
