/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.MenuItem;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author STIREN
 */
public class fManagement extends javax.swing.JFrame {

    /**
     * Creates new form fManagement
     */
    Toolkit tk =Toolkit.getDefaultToolkit();
    public int getSizeX()
    {
        return (int)jDesktopPane1.getSize().getWidth();
    }
    public int getSizeY()
    {
        return (int)jDesktopPane1.getSize().getHeight();
    }
    public fManagement() {
        initComponents(); 
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();  
        setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSale = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDiscount = new javax.swing.JMenuItem();
        jMenuItemSearchDiscount = new javax.swing.JMenuItem();
        jMenuCustomer = new javax.swing.JMenu();
        jMenuItemCustomer = new javax.swing.JMenuItem();
        jMenuListBook = new javax.swing.JMenu();
        jMenuItemListBook = new javax.swing.JMenuItem();
        jMenuItemSearchBook = new javax.swing.JMenuItem();
        jMenuStock = new javax.swing.JMenu();
        jMenuItemStock = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemReportRevenue = new javax.swing.JMenuItem();
        jMenuItemInventory = new javax.swing.JMenuItem();
        jMenuStaff = new javax.swing.JMenu();
        jMenuItemStaff = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuRule = new javax.swing.JMenu();
        jMenuItemRule = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHẦN MỀM QUẢN LÍ NHÀ SÁCH");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        jMenu1.setText("Bán hàng");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu1.setName("jMenuSale"); // NOI18N

        jMenuItemSale.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemSale.setText("Bán hàng");
        jMenuItemSale.setName("jMenuItemSale"); // NOI18N
        jMenuItemSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaleActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSale);

        jMenu2.setText("Khuyến mãi");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItemDiscount.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemDiscount.setText("Quản lí khuyến mãi");
        jMenuItemDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDiscountActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDiscount);

        jMenuItemSearchDiscount.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemSearchDiscount.setText("Tra cứu khuyến mãi");
        jMenuItemSearchDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchDiscountActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSearchDiscount);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        jMenuCustomer.setText("Khách hàng");
        jMenuCustomer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuCustomer.setName("jMenuCustomer"); // NOI18N
        jMenuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCustomerActionPerformed(evt);
            }
        });

        jMenuItemCustomer.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemCustomer.setText("Khách hàng");
        jMenuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jMenuItemCustomer);

        jMenuBar1.add(jMenuCustomer);

        jMenuListBook.setText("Danh mục sách");
        jMenuListBook.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuListBook.setName("jMenuListBook"); // NOI18N

        jMenuItemListBook.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemListBook.setText("Quản lý danh mục sách");
        jMenuItemListBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListBookActionPerformed(evt);
            }
        });
        jMenuListBook.add(jMenuItemListBook);

        jMenuItemSearchBook.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemSearchBook.setText("Tra cứu sách");
        jMenuItemSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchBookActionPerformed(evt);
            }
        });
        jMenuListBook.add(jMenuItemSearchBook);

        jMenuBar1.add(jMenuListBook);

        jMenuStock.setText("Nhập sách");
        jMenuStock.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuStock.setName("jMenuStock"); // NOI18N

        jMenuItemStock.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemStock.setText("Nhập sách");
        jMenuItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStockActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemStock);

        jMenuBar1.add(jMenuStock);

        jMenu5.setText("Báo cáo");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu5.setName("jMenuReport"); // NOI18N

        jMenuItemReportRevenue.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemReportRevenue.setText("Báo cáo doanh thu");
        jMenuItemReportRevenue.setName("jMenuItemReportRevenue"); // NOI18N
        jMenuItemReportRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportRevenueActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemReportRevenue);

        jMenuItemInventory.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemInventory.setText("Báo cáo tồn kho");
        jMenuItemInventory.setName("jMenuItemInventory"); // NOI18N
        jMenuItemInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInventoryActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemInventory);

        jMenuBar1.add(jMenu5);

        jMenuStaff.setText("Nhân viên");
        jMenuStaff.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuStaff.setName("jMenuStaff"); // NOI18N

        jMenuItemStaff.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemStaff.setText("Nhân viên");
        jMenuItemStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStaffActionPerformed(evt);
            }
        });
        jMenuStaff.add(jMenuItemStaff);

        jMenuBar1.add(jMenuStaff);

        jMenuUser.setText("Thông tin tài khoản");
        jMenuUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuUser.setName("jMenuUser"); // NOI18N

        jMenuItemUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemUser.setText("Người dùng");
        jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemUser);

        jMenuBar1.add(jMenuUser);

        jMenuRule.setText("Quy định");
        jMenuRule.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        jMenuItemRule.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItemRule.setText("Quy định");
        jMenuItemRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRuleActionPerformed(evt);
            }
        });
        jMenuRule.add(jMenuItemRule);

        jMenuBar1.add(jMenuRule);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaleActionPerformed
        // TODO add your handling code here:
        fSales f = new fSales();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemSaleActionPerformed

    private void jMenuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCustomerActionPerformed
        
        
    }//GEN-LAST:event_jMenuCustomerActionPerformed

    private void jMenuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerActionPerformed
        // TODO add your handling code here:
        fCustomer f = new fCustomer();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemCustomerActionPerformed

    private void jMenuItemListBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListBookActionPerformed
        // TODO add your handling code here:
        fListBook f = new fListBook();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemListBookActionPerformed

    private void jMenuItemSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchBookActionPerformed
        // TODO add your handling code here:
        fSearchBook f = new fSearchBook();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemSearchBookActionPerformed

    private void jMenuItemDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiscountActionPerformed
        // TODO add your handling code here:
        fDiscount f = new fDiscount();
        f.setSize(this.getSizeX(), this.getSizeY());
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemDiscountActionPerformed

    private void jMenuItemSearchDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchDiscountActionPerformed
        // TODO add your handling code here:
        fSearchDiscount f = new fSearchDiscount();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemSearchDiscountActionPerformed

    private void jMenuItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStockActionPerformed
        // TODO add your handling code here:
        fStock f = new fStock();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemStockActionPerformed

    private void jMenuItemReportRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportRevenueActionPerformed
        // TODO add your handling code here:
        fReportRevenue f = new fReportRevenue();
       f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemReportRevenueActionPerformed

    private void jMenuItemInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInventoryActionPerformed
        // TODO add your handling code here:
        fReportInventory f = new fReportInventory();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemInventoryActionPerformed

    private void jMenuItemStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStaffActionPerformed
        // TODO add your handling code here:
        fStaff f = new fStaff();
        f.setSize(this.getSizeX(), this.getSizeY());
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemStaffActionPerformed

    private void jMenuItemRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRuleActionPerformed
        // TODO add your handling code here:
        fRule f = new fRule();
        f.setSize(this.getSizeX(), this.getSizeY());;
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemRuleActionPerformed

    private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserActionPerformed
        // TODO add your handling code here:
        fUser f =new fUser();
        f.setSize(this.getSizeX(), this.getSizeY());;
        this.jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCustomer;
    private javax.swing.JMenuItem jMenuItemCustomer;
    private javax.swing.JMenuItem jMenuItemDiscount;
    private javax.swing.JMenuItem jMenuItemInventory;
    private javax.swing.JMenuItem jMenuItemListBook;
    private javax.swing.JMenuItem jMenuItemReportRevenue;
    private javax.swing.JMenuItem jMenuItemRule;
    private javax.swing.JMenuItem jMenuItemSale;
    private javax.swing.JMenuItem jMenuItemSearchBook;
    private javax.swing.JMenuItem jMenuItemSearchDiscount;
    private javax.swing.JMenuItem jMenuItemStaff;
    private javax.swing.JMenuItem jMenuItemStock;
    private javax.swing.JMenuItem jMenuItemUser;
    private javax.swing.JMenu jMenuListBook;
    private javax.swing.JMenu jMenuRule;
    private javax.swing.JMenu jMenuStaff;
    private javax.swing.JMenu jMenuStock;
    private javax.swing.JMenu jMenuUser;
    // End of variables declaration//GEN-END:variables
}
