/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BillBLL;
import BLL.BillInfoBLL;
import BLL.BookBLL;
import BLL.CustomerBLL;
import BLL.StaffBLL;
import Entity.Bill;
import Entity.Customer;
import Entity.Staff;
import Utilties.ControlFormat;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fSales extends javax.swing.JInternalFrame {

    /**
     * Creates new form fSales
     */
    private int flag = 0;
    ControlFormat control = new ControlFormat();
    BillBLL billBLL = new BillBLL();
    BillInfoBLL billinfoBLL = new BillInfoBLL();
    StaffBLL staffBLL = new StaffBLL();
    CustomerBLL customerBLL = new CustomerBLL();
    BookBLL bookBLL = new BookBLL();
    
    public fSales() {
        initComponents();
        txaBill.setVisible(false);
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txfIDCustomerBill = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txfNameCustomerBill = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txfTotalPriceBill = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txfTotalPayBill = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txfIDBill = new javax.swing.JTextField();
        jDChBillDate = new com.toedter.calendar.JDateChooser();
        cbIDStaffBill = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txfVATBill = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txfDiscountBill = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txfNameStaffBill = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txfStatusBill = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnAddBill = new javax.swing.JButton();
        btnEditBill = new javax.swing.JButton();
        btnSaveBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBill = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jDChSearchBill = new com.toedter.calendar.JDateChooser();
        btnSearchBill = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbIDBill_BillInfo = new javax.swing.JComboBox<>();
        txfIDBookBillInfo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAddBillInfo = new javax.swing.JButton();
        btnEditBillInfo = new javax.swing.JButton();
        btnDelBillInfo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbAmountBillInfo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txfTotalPriceBillInfo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txfPriceBillInfo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txfTotalPayBillInfo = new javax.swing.JTextField();
        txfDiscountBillInfo = new javax.swing.JTextField();
        txfVATBillInfo = new javax.swing.JTextField();
        txfRepayBillInfo = new javax.swing.JTextField();
        txfCashBillInfo = new javax.swing.JTextField();
        btnPayBillInfo = new javax.swing.JButton();
        btnSaveBillInfo = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txfPriceBookBillInfo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txfNameBook = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jDChSearchBillInfo = new com.toedter.calendar.JDateChooser();
        btnSearchBillInfo = new javax.swing.JButton();
        btnPrintBillInfo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBillInfo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaBill = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();

        setClosable(true);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("HÓA ĐƠN");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(486, 0, 147, 37);

        jPanel5.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Mã nhân viên");

        txfIDCustomerBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfIDCustomerBill.setName("txfIDCustomerBill"); // NOI18N
        txfIDCustomerBill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfIDCustomerBillKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Mã khách hàng");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Tên khách hàng");

        txfNameCustomerBill.setEditable(false);
        txfNameCustomerBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Thuế VAT");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Trị giá");

        txfTotalPriceBill.setEditable(false);
        txfTotalPriceBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Tổng tiền");

        txfTotalPayBill.setEditable(false);
        txfTotalPayBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("Số hóa đơn");

        txfIDBill.setEditable(false);
        txfIDBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jDChBillDate.setDateFormatString("dd-MM-yyyy");
        jDChBillDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cbIDStaffBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbIDStaffBill.setName("cbIDStaffBill"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setText("Ngày hóa đơn");

        txfVATBill.setEditable(false);
        txfVATBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 204));
        jLabel22.setText("Khuyến mãi");

        txfDiscountBill.setEditable(false);
        txfDiscountBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 204));
        jLabel23.setText("Tên nhân viên");

        txfNameStaffBill.setEditable(false);
        txfNameStaffBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 204));
        jLabel27.setText("Trạng thái");

        txfStatusBill.setEditable(false);
        txfStatusBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfStatusBill.setText("Chưa thanh toán");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfIDBill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfNameStaffBill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfTotalPayBill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfTotalPriceBill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfDiscountBill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfVATBill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfNameCustomerBill, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbIDStaffBill, javax.swing.GroupLayout.Alignment.TRAILING, 0, 203, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(txfIDCustomerBill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDChBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfStatusBill)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txfIDBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfStatusBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDChBillDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfIDCustomerBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNameCustomerBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbIDStaffBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNameStaffBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfVATBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfDiscountBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTotalPriceBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txfTotalPayBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(10, 39, 379, 484);

        jPanel7.setOpaque(false);

        btnAddBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddBill.setForeground(new java.awt.Color(0, 0, 204));
        btnAddBill.setText("THÊM");
        btnAddBill.setName("btnAddBill"); // NOI18N
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });

        btnEditBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditBill.setForeground(new java.awt.Color(0, 0, 204));
        btnEditBill.setText("CẬP NHẬT");
        btnEditBill.setName("btnEditBill"); // NOI18N
        btnEditBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBillActionPerformed(evt);
            }
        });

        btnSaveBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveBill.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveBill.setText("LƯU");
        btnSaveBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnEditBill)
                .addGap(40, 40, 40)
                .addComponent(btnSaveBill, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBill)
                    .addComponent(btnEditBill)
                    .addComponent(btnSaveBill))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(10, 546, 427, 36);

        jTableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Số hóa đơn", "Mã nhân viên", "Mã khách hàng", "Ngày hóa đơn", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTableBill.setName("jTableBill"); // NOI18N
        jTableBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBill);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(486, 197, 742, 385);

        jPanel4.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 204));
        jLabel21.setText("Tìm hóa đơn theo ngày");

        jDChSearchBill.setDateFormatString("dd-MM-yyyy");
        jDChSearchBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchBill.setText("TÌM KIẾM");
        btnSearchBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jDChSearchBill, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnSearchBill)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchBill)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDChSearchBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(486, 87, 479, 70);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        jPanel3.add(jLabel29);
        jLabel29.setBounds(0, 0, 1460, 750);

        jTabbedPane1.addTab("Hóa đơn", jPanel3);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CHI TIẾT HÓA ĐƠN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(486, 30, 292, 37);

        jPanel6.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Số hóa đơn");

        cbIDBill_BillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbIDBill_BillInfo.setName("cbIDBill_BillInfo"); // NOI18N
        cbIDBill_BillInfo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIDBill_BillInfoItemStateChanged(evt);
            }
        });

        txfIDBookBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfIDBookBillInfo.setName("txfIDBookBillInfo"); // NOI18N
        txfIDBookBillInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfIDBookBillInfoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Mã sách");

        btnAddBillInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddBillInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnAddBillInfo.setText("THÊM");
        btnAddBillInfo.setName("btnAddBillInfo"); // NOI18N
        btnAddBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillInfoActionPerformed(evt);
            }
        });

        btnEditBillInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditBillInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnEditBillInfo.setText("CẬP NHẬT");
        btnEditBillInfo.setName("btnEditBillInfo"); // NOI18N
        btnEditBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBillInfoActionPerformed(evt);
            }
        });

        btnDelBillInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelBillInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnDelBillInfo.setText("XÓA");
        btnDelBillInfo.setName("btnDelIfoBill"); // NOI18N
        btnDelBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelBillInfoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Số lượng");

        cbAmountBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAmountBillInfo.setName("cbAmountBillInfo"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Thành tiền");

        txfTotalPriceBillInfo.setEditable(false);
        txfTotalPriceBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfTotalPriceBillInfo.setText("0");
        txfTotalPriceBillInfo.setName("txfTotalPriceBillInfo"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Trị giá");

        txfPriceBillInfo.setEditable(false);
        txfPriceBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfPriceBillInfo.setText("0");
        txfPriceBillInfo.setName("txfPriceBillInfo"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Chiết khấu");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Tiền mặt thanh toán");
        jLabel11.setName(""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Tiền trả lại");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Tổng tiền");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Thuế VAT");

        txfTotalPayBillInfo.setEditable(false);
        txfTotalPayBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfTotalPayBillInfo.setText("0");
        txfTotalPayBillInfo.setName("txfTotalPayBillInfo"); // NOI18N

        txfDiscountBillInfo.setEditable(false);
        txfDiscountBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfDiscountBillInfo.setText("0");
        txfDiscountBillInfo.setName("txfDiscountBillInfo"); // NOI18N

        txfVATBillInfo.setEditable(false);
        txfVATBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfVATBillInfo.setText("0");
        txfVATBillInfo.setName("txfVATBillInfo"); // NOI18N

        txfRepayBillInfo.setEditable(false);
        txfRepayBillInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfRepayBillInfo.setName("txfRepayBillInfo"); // NOI18N

        txfCashBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfCashBillInfo.setName("txfCashBillInfo"); // NOI18N

        btnPayBillInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPayBillInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnPayBillInfo.setText("Thanh toán");
        btnPayBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillInfoActionPerformed(evt);
            }
        });

        btnSaveBillInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveBillInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnSaveBillInfo.setText("LƯU");
        btnSaveBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillInfoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setText("Giá bán");

        txfPriceBookBillInfo.setEditable(false);
        txfPriceBookBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 204));
        jLabel26.setText("Tên sách");

        txfNameBook.setEditable(false);
        txfNameBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel28.setText("____________________________________________________________");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfTotalPriceBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfPriceBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAmountBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfPriceBookBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbIDBill_BillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfIDBookBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(121, 121, 121)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnEditBillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAddBillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDelBillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnSaveBillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txfVATBillInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txfDiscountBillInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txfTotalPayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txfCashBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnPayBillInfo)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txfRepayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbIDBill_BillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfIDBookBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBillInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txfNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBillInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPriceBookBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(btnDelBillInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbAmountBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveBillInfo))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txfPriceBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTotalPriceBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfDiscountBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfVATBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txfTotalPayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txfCashBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayBillInfo)
                    .addComponent(jLabel12)
                    .addComponent(txfRepayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 77, 587, 570);

        jPanel8.setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 204));
        jLabel25.setText("Tìm chi tiết hóa đơn theo ngày");

        jDChSearchBillInfo.setDateFormatString("dd-MM-yyyy");

        btnSearchBillInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSearchBillInfo.setText("TÌM KIẾM");
        btnSearchBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBillInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDChSearchBillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(btnSearchBillInfo)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchBillInfo)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDChSearchBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(637, 85, 395, 80);

        btnPrintBillInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrintBillInfo.setForeground(new java.awt.Color(0, 0, 204));
        btnPrintBillInfo.setText("IN HÓA ĐƠN");
        btnPrintBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrintBillInfo);
        btnPrintBillInfo.setBounds(637, 171, 125, 25);

        jTableBillInfo.setBorder(new javax.swing.border.MatteBorder(null));
        jTableBillInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Giá", "Số lượng", "Thành tiền"
            }
        ));
        jTableBillInfo.setName("jTableBillInfo"); // NOI18N
        jTableBillInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBillInfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBillInfo);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(637, 225, 685, 359);

        txaBill.setColumns(20);
        txaBill.setRows(5);
        jScrollPane4.setViewportView(txaBill);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(1093, 85, 37, 18);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhbia7.jpg"))); // NOI18N
        jPanel1.add(jLabel30);
        jLabel30.setBounds(0, 0, 1460, 850);

        jTabbedPane1.addTab("Chi tiết hóa đơn", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Load()
    {
        int idbill;
        if(cbIDBill_BillInfo.getSelectedItem() == null)
            idbill = 0;
        else idbill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
        control.bindingBill(jTableBill, billBLL.LoadBill());
        //control.bindingBillInfo(jTableBillInfo, billinfoBLL.LoadBillInfo(idbill));
        
        //Lấy giá trị hóa đơn theo số hóa đơn trong CTHD
        txfTotalPriceBillInfo.setText(String.valueOf(billBLL.getTotalPriceByIDBill(idbill)));
        txfDiscountBillInfo.setText(String.valueOf(billBLL.getDiscountByIDBill(idbill)));
        txfVATBillInfo.setText(String.valueOf(billBLL.getVATByIDBill(idbill)));
        txfTotalPayBillInfo.setText(String.valueOf(billBLL.getTotalPayByIDBill(idbill)));
        
        jDChBillDate.setDate(Today);
        cbIDStaffBill.removeAllItems();
        cbIDBill_BillInfo.removeAllItems();
        cbAmountBillInfo.removeAllItems();
        
        for(Staff staff : staffBLL.LoadStaff())
        {
            cbIDStaffBill.addItem(String.valueOf(staff.getID()));
        }
        for(Bill bill : billBLL.LoadIDBill())
        {
            cbIDBill_BillInfo.addItem(String.valueOf(bill.getIDBill()));
        }
        
        
        for(int i=1; i<=20; i++)
            cbAmountBillInfo.addItem(String.valueOf(i));
        
    }
    
    private void cbIDBill_BillInfoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIDBill_BillInfoItemStateChanged
        // TODO add your handling code here:
        int idbill;
        if(cbIDBill_BillInfo.getSelectedItem() == null)
            idbill = 0;
        else idbill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
        //control.bindingBillInfo(jTableBillInfo, billinfoBLL.LoadBillInfo(idbill));
        //Xét lại các giá trị của hóa đơn khi thay đổi số hóa đơn tại cb số hóa đơn trong CTHD
        txfTotalPriceBillInfo.setText(String.valueOf(billBLL.getTotalPriceByIDBill(idbill)));
        txfDiscountBillInfo.setText(String.valueOf(billBLL.getDiscountByIDBill(idbill)));
        txfVATBillInfo.setText(String.valueOf(billBLL.getVATByIDBill(idbill)));
        txfTotalPayBillInfo.setText(String.valueOf(billBLL.getTotalPayByIDBill(idbill)));
    }//GEN-LAST:event_cbIDBill_BillInfoItemStateChanged

    private void btnAddBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillInfoActionPerformed
        // TODO add your handling code here:
        ClearTextBillInfo();
        btnAddBillInfo.setEnabled(false);
        btnDelBillInfo.setEnabled(false);
        btnEditBillInfo.setEnabled(false);
        btnSaveBillInfo.setEnabled(true);
        flag = 4;
    }//GEN-LAST:event_btnAddBillInfoActionPerformed

    private void btnEditBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBillInfoActionPerformed
        // TODO add your handling code here:
        btnAddBillInfo.setEnabled(false);
        btnDelBillInfo.setEnabled(false);
        btnEditBillInfo.setEnabled(false);
        btnSaveBillInfo.setEnabled(true);
        flag = 5;
    }//GEN-LAST:event_btnEditBillInfoActionPerformed

    private void btnDelBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelBillInfoActionPerformed
        // TODO add your handling code here:
        btnAddBillInfo.setEnabled(false);
        btnDelBillInfo.setEnabled(false);
        btnEditBillInfo.setEnabled(false);
        btnSaveBillInfo.setEnabled(true);
        flag = 6;
    }//GEN-LAST:event_btnDelBillInfoActionPerformed

    private void btnPayBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillInfoActionPerformed
        // TODO add your handling code here:
        int idbill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
        control.bindingBillInfo(jTableBillInfo, billinfoBLL.LoadBillInfo(idbill));
        if(billBLL.getStatusBill(idbill).equals("Đã thanh toán"))
            JOptionPane.showMessageDialog(this, "Hóa đơn này đã thanh toán");
        else{ 
        if(txfCashBillInfo.getText().equals(""))
        JOptionPane.showMessageDialog(this, "Vui lòng nhập tiền mặt khách trả");
        else{
            float Repay = Float.parseFloat(txfCashBillInfo.getText()) - Float.parseFloat(txfTotalPayBillInfo.getText());
            if(Repay < 0)
            JOptionPane.showMessageDialog(this, "Không đủ tiền trả");
            else
            {
                txfRepayBillInfo.setText(String.valueOf(Repay));
                UpdateStatusBill();
                control.bindingBill(jTableBill, billBLL.LoadBill());
                cbIDBill_BillInfo.removeAllItems();
                for(Bill bill : billBLL.LoadIDBill())
                    cbIDBill_BillInfo.addItem(String.valueOf(bill.getIDBill()));
            }
        }
        }
    }//GEN-LAST:event_btnPayBillInfoActionPerformed

    private void btnSaveBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillInfoActionPerformed
        // TODO add your handling code here:
        if(flag == 4)
        {
            if(InsertBillInfo())
            {
                btnAddBillInfo.setEnabled(true);
                btnDelBillInfo.setEnabled(true);
                btnEditBillInfo.setEnabled(true);
                btnSaveBillInfo.setEnabled(false);
                int idbill;
                if(cbIDBill_BillInfo.getSelectedItem() == null)
                idbill = 0;
                else idbill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
                control.bindingBillInfo(jTableBillInfo, billinfoBLL.LoadBillInfo(idbill));
                control.bindingBill(jTableBill, billBLL.LoadBill());
                //Xét lại các giá trị của hóa đơn khi thêm CTHD
                txfTotalPayBillInfo.setText(String.valueOf(billBLL.getTotalPayByIDBill(idbill)));
                txfDiscountBillInfo.setText(String.valueOf(billBLL.getDiscountByIDBill(idbill)));
                txfTotalPriceBillInfo.setText(String.valueOf(billBLL.getTotalPriceByIDBill(idbill)));
                ClearTextBillInfo();
            }
        }
        if(flag == 5)
        {
            if(UpdateBillInfo())
            {
                btnAddBillInfo.setEnabled(true);
                btnDelBillInfo.setEnabled(true);
                btnEditBillInfo.setEnabled(true);
                btnSaveBillInfo.setEnabled(false);
                int idbill;
                if(cbIDBill_BillInfo.getSelectedItem() == null)
                idbill = 0;
                else idbill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
                control.bindingBillInfo(jTableBillInfo, billinfoBLL.LoadBillInfo(idbill));
                control.bindingBill(jTableBill, billBLL.LoadBill());
                //Xét lại các giá trị của hóa đơn khi sửa CTHD
                txfTotalPayBillInfo.setText(String.valueOf(billBLL.getTotalPayByIDBill(idbill)));
                txfDiscountBillInfo.setText(String.valueOf(billBLL.getDiscountByIDBill(idbill)));
                txfTotalPriceBillInfo.setText(String.valueOf(billBLL.getTotalPriceByIDBill(idbill)));
                ClearTextBillInfo();
            }
        }
        if(flag == 6)
        {
            DeleteBillInfo();
            btnAddBillInfo.setEnabled(true);
            btnDelBillInfo.setEnabled(true);
            btnEditBillInfo.setEnabled(true);
            btnSaveBillInfo.setEnabled(false);
            int idbill;
            if(cbIDBill_BillInfo.getSelectedItem() == null)
            idbill = 0;
            else idbill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
            control.bindingBillInfo(jTableBillInfo, billinfoBLL.LoadBillInfo(idbill));
            control.bindingBill(jTableBill, billBLL.LoadBill());
            //Xét lại các giá trị của hóa đơn khi xóa CTHD
            txfTotalPayBillInfo.setText(String.valueOf(billBLL.getTotalPayByIDBill(idbill)));
            txfDiscountBillInfo.setText(String.valueOf(billBLL.getDiscountByIDBill(idbill)));
            txfTotalPriceBillInfo.setText(String.valueOf(billBLL.getTotalPriceByIDBill(idbill)));
            ClearTextBillInfo();
        }
    }//GEN-LAST:event_btnSaveBillInfoActionPerformed

    private void btnSearchBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBillInfoActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date search = jDChSearchBillInfo.getDate();
        String key;
        if(jDChSearchBillInfo.getDate() == null)
        key = "";
        else
        key = formatter.format(search);
        control.bindingBillInfo(jTableBillInfo, billinfoBLL.SearchBillInfo(key));
        jDChSearchBill.setDate(null);
    }//GEN-LAST:event_btnSearchBillInfoActionPerformed

    private void btnPrintBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillInfoActionPerformed
        txaBill.setText("");
        txaBill.append("\t \t  NHÀ SÁCH TYQ \n \n");
        txaBill.append("Địa chỉ: Khu phố 6, P.Linh Trung, Q.Thủ Đức, TP.Hồ Chí Minh. \n" +
            "SĐT: 0962 111 222 \n" +
            "Email: nhasachTYQ@gmail.com \n \n");
        txaBill.append("\t \t HÓA ĐƠN THANH TOÁN \n \n");

        int idbill;
        if(cbIDBill_BillInfo.getSelectedItem() == null)
        idbill = 0;
        else idbill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());

        if(billBLL.getIDCustomerByIDBill(idbill) == 0)
        txaBill.append("Mã khách hàng: \n");
        else
        txaBill.append("Mã khách hàng: " + billBLL.getIDCustomerByIDBill(idbill) + "\n");
        txaBill.append("Nhân viên thu ngân: " + billBLL.getNameStaffByIDBill(idbill) + "\n");
        txaBill.append("Ngày hóa đơn: " + billBLL.getDateBillByIDBill(idbill) + "\n");
        txaBill.append("Số hóa đơn: " + idbill + "\n \n");
        txaBill.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        txaBill.append("Mã sách \t Tên sách \t\t Giá bán \t Số lượng \t Thành tiền \n");
        txaBill.append("--------------------------------------------------------------------------------------------------------------------------------\n");

         control.bindingBillInfo(jTableBillInfo, billinfoBLL.LoadBillInfo(idbill));
        int row = jTableBillInfo.getRowCount();
        int column = jTableBillInfo.getColumnCount();
        for(int i=0; i < row; i++)
        {
            for(int j=1; j < column; j++)
            {
                txaBill.append(jTableBillInfo.getValueAt(i, j).toString() + "\t");
                if(j == 2)
                    txaBill.append("\t");
            }
            txaBill.append("\n");
        }
        txaBill.append("--------------------------------------------------------------------------------------------------------------------------------\n");
        txaBill.append("\nTrị giá: " + txfTotalPriceBillInfo.getText() + "\n" +
            "Chiết khấu: " + txfDiscountBillInfo.getText() + "\n" +
            "VAT: " + txfVATBillInfo.getText() + "\n" +
            "Tổng tiền: " + txfTotalPayBillInfo.getText() + "\n" +
            "Tiền mặt thanh toán: " + txfCashBillInfo.getText() + "\n" +
            "Tiền trả lại khách: " + txfRepayBillInfo.getText() + "\n \n" +
            "Cám ơn và hẹn gặp lại quý khách!");
        try {
            txaBill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(fSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintBillInfoActionPerformed

    private void jTableBillInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBillInfoMouseClicked
        // TODO add your handling code here:
        int row = jTableBillInfo.getSelectedRow();
        cbIDBill_BillInfo.setSelectedItem(jTableBillInfo.getValueAt(row, 0).toString());
        txfIDBookBillInfo.setText(jTableBillInfo.getValueAt(row, 1).toString());
        txfNameBook.setText(jTableBillInfo.getValueAt(row, 2).toString());
        txfPriceBookBillInfo.setText(jTableBillInfo.getValueAt(row, 3).toString());
        cbAmountBillInfo.setSelectedItem(jTableBillInfo.getValueAt(row, 4).toString());
        txfPriceBillInfo.setText(jTableBillInfo.getValueAt(row, 5).toString());
        
        txfCashBillInfo.setText("");
        txfRepayBillInfo.setText("");
    }//GEN-LAST:event_jTableBillInfoMouseClicked

    private void txfIDBookBillInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfIDBookBillInfoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) || txfIDBookBillInfo.getText().length() >= 10)
            evt.consume();
    }//GEN-LAST:event_txfIDBookBillInfoKeyTyped

    private void btnSearchBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBillActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date search = jDChSearchBill.getDate();
        String key;
        if(jDChSearchBill.getDate() == null)
        key = "";
        else
        key = formatter.format(search);
        control.bindingBill(jTableBill, billBLL.SearchBill(key));
        jDChSearchBill.setDate(null);
    }//GEN-LAST:event_btnSearchBillActionPerformed

    private void jTableBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBillMouseClicked
        // TODO add your handling code here:
        //         String bookcategogy =jTableBookInfo.getValueAt(row, 1).toString();
        //        if(jTableBookInfo.getValueAt(row, 1).toString().equals(bookcategogy))
        //        cbNameCategogyBookInfo.setSelectedItem(bookcategogy);
        //
        int row = jTableBill.getSelectedRow();
        txfIDBill.setText(jTableBill.getValueAt(row, 0).toString());
        txfStatusBill.setText(jTableBill.getValueAt(row, 1).toString());
        jDChBillDate.setDate((Date) jTableBill.getModel().getValueAt(row, 2));
        txfIDCustomerBill.setText(jTableBill.getValueAt(row, 3).toString());
        txfNameCustomerBill.setText(jTableBill.getValueAt(row, 4).toString());

        cbIDStaffBill.setSelectedItem(jTableBill.getValueAt(row, 5).toString());
        txfNameStaffBill.setText(jTableBill.getValueAt(row, 6).toString());
        txfVATBill.setText(jTableBill.getValueAt(row, 7).toString());
        txfDiscountBill.setText(jTableBill.getValueAt(row, 8).toString());
        txfTotalPriceBill.setText(jTableBill.getValueAt(row, 9).toString());
        txfTotalPayBill.setText(jTableBill.getValueAt(row, 10).toString());
    }//GEN-LAST:event_jTableBillMouseClicked

    private void btnSaveBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillActionPerformed
        // TODO add your handling code here:
        if(flag == 1)
        {
            InsertBill();
            btnAddBill.setEnabled(true);
            btnEditBill.setEnabled(true);
            btnSaveBill.setEnabled(false);
            control.bindingBill(jTableBill, billBLL.LoadBill());
            cbIDBill_BillInfo.removeAllItems();
            for(Bill bill : billBLL.LoadIDBill())
            cbIDBill_BillInfo.addItem(String.valueOf(bill.getIDBill()));
            ClearTextBill();
        }
        if(flag == 2)
        {
            UpdateBill();
            btnAddBill.setEnabled(true);
            btnEditBill.setEnabled(true);
            btnSaveBill.setEnabled(false);
            control.bindingBill(jTableBill, billBLL.LoadBill());
            ClearTextBill();
        }
    }//GEN-LAST:event_btnSaveBillActionPerformed

    private void btnEditBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBillActionPerformed
        // TODO add your handling code here:
        btnAddBill.setEnabled(false);
        btnEditBill.setEnabled(false);
        btnSaveBill.setEnabled(true);
        flag = 2;
    }//GEN-LAST:event_btnEditBillActionPerformed

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
        // TODO add your handling code here:
        ClearTextBill();
        btnAddBill.setEnabled(false);
        btnEditBill.setEnabled(false);
        btnSaveBill.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddBillActionPerformed

    private void txfIDCustomerBillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfIDCustomerBillKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) || txfIDCustomerBill.getText().length() >= 10)
        evt.consume();
    }//GEN-LAST:event_txfIDCustomerBillKeyTyped
    Date Today = new java.util.Date();
    public void ClearTextBill()
    {
        txfIDBill.setText("");
        jDChBillDate.setDate(Today);
        txfIDCustomerBill.setText("");
        txfNameCustomerBill.setText("");
        txfNameStaffBill.setText("");
        txfVATBill.setText("");
        txfDiscountBill.setText("");
        txfTotalPriceBill.setText("");
        txfTotalPayBill.setText("");
    }
    
    //Thêm hóa đơn
    public void InsertBill()
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String BillDate = formatter.format(jDChBillDate.getDate());
        
        int IDCustomer;
        if(txfIDCustomerBill.getText().equals(""))
            IDCustomer = 0;
        else IDCustomer = Integer.parseInt(txfIDCustomerBill.getText());
        
        int IDStaff = Integer.parseInt(cbIDStaffBill.getSelectedItem().toString());
        
        if(customerBLL.TestIDCustomer(IDCustomer) == false)
            JOptionPane.showMessageDialog(this, "Mã khách hàng không tồn tại");
        else
        {
            if(billBLL.InsertBill(BillDate, IDCustomer, IDStaff))
            {
                //JOptionPane.showMessageDialog(this, "Thêm thành công hóa đơn");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại hóa đơn");
            }
        }
    }
    //Cập nhật hóa đơn
    public void UpdateBill()
    {
        int IDBill = Integer.parseInt(txfIDBill.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String BillDate = formatter.format(jDChBillDate.getDate());
        
        int IDCustomer;
        if(txfIDCustomerBill.getText().equals(""))
            IDCustomer = 0;
        else IDCustomer = Integer.parseInt(txfIDCustomerBill.getText());
        
        int IDStaff = Integer.parseInt(cbIDStaffBill.getSelectedItem().toString());
        
        if(billBLL.getStatusBill(IDBill).equals("Đã thanh toán"))
            JOptionPane.showMessageDialog(this, "Không được cập nhật hóa đơn đã thanh toán");
        else
        {
            if(customerBLL.TestIDCustomer(IDCustomer) == false)
                JOptionPane.showMessageDialog(this, "Mã khách hàng không tồn tại");
            else
            {
                if(billBLL.UpdateBill(IDBill, BillDate, IDCustomer, IDStaff))
                {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công hóa đơn");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại hóa đơn");
                }
            }                        
        }
    }
    //Cập nhật trạng thái hóa đơn sau khi thanh toán
    public void UpdateStatusBill()
    {       
        int IDBill;
        if(cbIDBill_BillInfo.getSelectedItem() == null)
            IDBill = 0;
        else IDBill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
        billBLL.UpdateStatusBill(IDBill);
    }
    
    //Xóa dữ liệu trong ô nhập CTHD
    public void ClearTextBillInfo()
    {
        txfIDBookBillInfo.setText("");
        txfNameBook.setText("");
        txfPriceBookBillInfo.setText("");
        txfPriceBillInfo.setText("");
    }
    
    //Thêm CTHD
    public boolean InsertBillInfo()
    {
        int IDBill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
        int IDBook;
        if(txfIDBookBillInfo.getText().equals(""))
            IDBook = 0;
        else 
            IDBook = Integer.parseInt(txfIDBookBillInfo.getText());
        int Amount = Integer.parseInt(cbAmountBillInfo.getSelectedItem().toString());
        
        
        
        if(txfIDBookBillInfo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Mã sách bắt buộc có");
            return false;
        }
        else if (billBLL.getStatusBill(IDBill).equals("Đã thanh toán"))
        {
            JOptionPane.showMessageDialog(this, "Không được thêm khi hóa đơn đã thanh toán");
            return true;
        }
        else
        {
            if(bookBLL.TestIDBook(IDBook) == false)
            {
                JOptionPane.showMessageDialog(this, "Mã sách không tồn tại");
                return false;
            }
            else
            {
                if(billinfoBLL.InsertBillInfo(IDBill, IDBook, Amount))
                {
                    //JOptionPane.showMessageDialog(this, "Thêm thành công chi tiết hóa đơn");
                    return true;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại chi tiết hóa đơn");
                    return false;
                }
            }                       
        }
    }
    //Cập nhật CTHD
    public boolean UpdateBillInfo()
    {
        int IDBill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
        int IDBook;
        if(txfIDBookBillInfo.getText().equals(""))
            IDBook = 0;
        else 
            IDBook = Integer.parseInt(txfIDBookBillInfo.getText());
        int Amount = Integer.parseInt(cbAmountBillInfo.getSelectedItem().toString());
        
        if(txfIDBookBillInfo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Mã sách bắt buộc có");
            return false;
        }
        else if (billBLL.getStatusBill(IDBill).equals("Đã thanh toán"))
        {
            JOptionPane.showMessageDialog(this, "Không được cập nhật khi hóa đơn đã thanh toán");
            return true;
        }
        else
        {
            if(billinfoBLL.UpdateBillInfo(IDBill, IDBook, Amount))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công chi tiết hóa đơn");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại chi tiết hóa đơn");
                return false;
            }
        }
    }
    
    //Xóa CTHD
    public void DeleteBillInfo()
    {
        int IDBill = Integer.parseInt(cbIDBill_BillInfo.getSelectedItem().toString());
        
        if (billBLL.getStatusBill(IDBill).equals("Đã thanh toán"))
        {
            JOptionPane.showMessageDialog(this, "Không được xóa khi hóa đơn đã thanh toán");
        }
        else
        {
            if(cbIDBill_BillInfo.getSelectedItem().toString().equals("") == false && txfIDBookBillInfo.getText().equals("") == false)
        {
            int IDBook = Integer.parseInt(txfIDBookBillInfo.getText());
            if(billinfoBLL.DeleteBillInfo(IDBill, IDBook))
                JOptionPane.showMessageDialog(this, "Xóa thành công hóa đơn");
        }
        else
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnAddBillInfo;
    private javax.swing.JButton btnDelBillInfo;
    private javax.swing.JButton btnEditBill;
    private javax.swing.JButton btnEditBillInfo;
    private javax.swing.JButton btnPayBillInfo;
    private javax.swing.JButton btnPrintBillInfo;
    private javax.swing.JButton btnSaveBill;
    private javax.swing.JButton btnSaveBillInfo;
    private javax.swing.JButton btnSearchBill;
    private javax.swing.JButton btnSearchBillInfo;
    private javax.swing.JComboBox<String> cbAmountBillInfo;
    private javax.swing.JComboBox<String> cbIDBill_BillInfo;
    private javax.swing.JComboBox<String> cbIDStaffBill;
    private com.toedter.calendar.JDateChooser jDChBillDate;
    private com.toedter.calendar.JDateChooser jDChSearchBill;
    private com.toedter.calendar.JDateChooser jDChSearchBillInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBill;
    private javax.swing.JTable jTableBillInfo;
    private javax.swing.JTextArea txaBill;
    private javax.swing.JTextField txfCashBillInfo;
    private javax.swing.JTextField txfDiscountBill;
    private javax.swing.JTextField txfDiscountBillInfo;
    private javax.swing.JTextField txfIDBill;
    private javax.swing.JTextField txfIDBookBillInfo;
    private javax.swing.JTextField txfIDCustomerBill;
    private javax.swing.JTextField txfNameBook;
    private javax.swing.JTextField txfNameCustomerBill;
    private javax.swing.JTextField txfNameStaffBill;
    private javax.swing.JTextField txfPriceBillInfo;
    private javax.swing.JTextField txfPriceBookBillInfo;
    private javax.swing.JTextField txfRepayBillInfo;
    private javax.swing.JTextField txfStatusBill;
    private javax.swing.JTextField txfTotalPayBill;
    private javax.swing.JTextField txfTotalPayBillInfo;
    private javax.swing.JTextField txfTotalPriceBill;
    private javax.swing.JTextField txfTotalPriceBillInfo;
    private javax.swing.JTextField txfVATBill;
    private javax.swing.JTextField txfVATBillInfo;
    // End of variables declaration//GEN-END:variables
}
