/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BillBLL;
import BLL.CustomerBLL;
import Entity.Bill;
import Entity.Customer;
import Utilties.ControlFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fSales extends javax.swing.JInternalFrame {

    /**
     * Creates new form fSales
     */
    private int flag = 0;
    ControlFormat control = new ControlFormat();
    BillBLL billBILL = new BillBLL();
    CustomerBLL customerBLL = new CustomerBLL();
    
    public fSales() {
        initComponents();
        control.bindingBill(jTableBill, billBILL.LoadBill());
        jDChBillDate.setDate(Today);
        cbIDStaffBill.removeAllItems();
//        for(Staff staff: staffBLL.LoadStaff())
//        {
//            cbIDStaffBill.addItem(String.valueOf(staff.getIDStaff()));
//        }

        cbIDStaffBill.addItem("1");
        cbIDStaffBill.addItem("2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbIDBill_BillInfo = new javax.swing.JComboBox<>();
        txfIDBookBillInfo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAddBillInfo = new javax.swing.JButton();
        btnEditBillInfo = new javax.swing.JButton();
        btnDelBillInfo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbAmountBillInfo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txfTotalPriceBillInfo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txfPriceBillInfo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txfTotalPayBillInfo = new javax.swing.JTextField();
        txfDiscountBillInfo = new javax.swing.JTextField();
        txfVATBillInfo = new javax.swing.JTextField();
        txfRepayBillInfo = new javax.swing.JTextField();
        txfCashBillInfo = new javax.swing.JTextField();
        btnPayBillInfo = new javax.swing.JButton();
        btnSaveBillInfo = new javax.swing.JButton();
        btnPrintBillInfo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBillInfo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBill = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnAddBill = new javax.swing.JButton();
        btnEditBill = new javax.swing.JButton();
        btnDelBill = new javax.swing.JButton();
        btnSaveBill = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txfIDCustomerBill = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txfNameCustomerBill = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txfTotalPriceBill = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txfTotalPayBill = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txfIDBill = new javax.swing.JTextField();
        jDChBillDate = new com.toedter.calendar.JDateChooser();
        cbIDStaffBill = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txfVATBill = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cbDiscountBill = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jDChSearchBill = new com.toedter.calendar.JDateChooser();
        btnSearchBill = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N

        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("THÔNG TIN HÓA ĐƠN");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 33, 330, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Số hóa đơn");

        cbIDBill_BillInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbIDBill_BillInfo.setName("cbIDBill_BillInfo"); // NOI18N

        txfIDBookBillInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfIDBookBillInfo.setName("txfIDBookBillInfo"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Mã sách");

        btnAddBillInfo.setText("THÊM");
        btnAddBillInfo.setName("btnAddBillInfo"); // NOI18N

        btnEditBillInfo.setText("CẬP NHẬT");
        btnEditBillInfo.setName("btnEditBillInfo"); // NOI18N

        btnDelBillInfo.setText("XÓA");
        btnDelBillInfo.setName("btnDelIfoBill"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Số lượng");

        cbAmountBillInfo.setName("cbAmountBillInfo"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Thành tiền");

        txfTotalPriceBillInfo.setEditable(false);
        txfTotalPriceBillInfo.setText("0");
        txfTotalPriceBillInfo.setName("txfTotalPriceBillInfo"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Trị giá");

        txfPriceBillInfo.setEditable(false);
        txfPriceBillInfo.setText("0");
        txfPriceBillInfo.setName("txfPriceBillInfo"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Chiết khấu");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Tiền mặt thanh toán");
        jLabel11.setName(""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Tiền trả lại");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Tổng tiền");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Thuế VAT");

        txfTotalPayBillInfo.setEditable(false);
        txfTotalPayBillInfo.setText("0");
        txfTotalPayBillInfo.setName("txfTotalPayBillInfo"); // NOI18N

        txfDiscountBillInfo.setEditable(false);
        txfDiscountBillInfo.setText("0");
        txfDiscountBillInfo.setName("txfDiscountBillInfo"); // NOI18N

        txfVATBillInfo.setEditable(false);
        txfVATBillInfo.setText("0");
        txfVATBillInfo.setName("txfVATBillInfo"); // NOI18N

        txfRepayBillInfo.setEditable(false);
        txfRepayBillInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfRepayBillInfo.setName("txfRepayBillInfo"); // NOI18N

        txfCashBillInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfCashBillInfo.setName("txfCashBillInfo"); // NOI18N

        btnPayBillInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPayBillInfo.setText("Thanh toán");

        btnSaveBillInfo.setText("LƯU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPayBillInfo)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(9, 9, 9)
                                    .addComponent(txfCashBillInfo))
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txfIDBookBillInfo)
                                        .addComponent(cbIDBill_BillInfo, 0, 200, Short.MAX_VALUE)
                                        .addComponent(cbAmountBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txfPriceBillInfo)))
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                    .addComponent(txfRepayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnAddBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnEditBillInfo)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSaveBillInfo))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfTotalPayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txfVATBillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(txfDiscountBillInfo)
                                .addComponent(txfTotalPriceBillInfo)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cbIDBill_BillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfIDBookBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbAmountBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPriceBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBillInfo)
                    .addComponent(btnEditBillInfo)
                    .addComponent(btnDelBillInfo)
                    .addComponent(btnSaveBillInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTotalPriceBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txfDiscountBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txfVATBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txfTotalPayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txfCashBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnPayBillInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txfRepayBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(10, 76, 420, 557);

        btnPrintBillInfo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnPrintBillInfo.setText("IN HÓA ĐƠN");
        jPanel4.add(btnPrintBillInfo);
        btnPrintBillInfo.setBounds(486, 105, 129, 27);

        jTableBillInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Giá", "Số lượng", "Thành tiền"
            }
        ));
        jTableBillInfo.setName("jTableBillInfo"); // NOI18N
        jScrollPane2.setViewportView(jTableBillInfo);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(486, 172, 518, 397);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Thông tin hóa đơn", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("LẬP HÓA ĐƠN");

        jTableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Số hóa đơn", "Mã nhân viên", "Mã khách hàng", "Ngày hóa đơn", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTableBill.setName("jTableBill"); // NOI18N
        jTableBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBill);

        btnAddBill.setText("THÊM");
        btnAddBill.setName("btnAddBill"); // NOI18N
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });

        btnEditBill.setText("CẬP NHẬT");
        btnEditBill.setName("btnEditBill"); // NOI18N
        btnEditBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBillActionPerformed(evt);
            }
        });

        btnDelBill.setText("XÓA");
        btnDelBill.setName("btnDelBill"); // NOI18N
        btnDelBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelBillActionPerformed(evt);
            }
        });

        btnSaveBill.setText("LƯU");
        btnSaveBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditBill)
                .addGap(18, 18, 18)
                .addComponent(btnDelBill, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnSaveBill)
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBill)
                    .addComponent(btnEditBill)
                    .addComponent(btnDelBill)
                    .addComponent(btnSaveBill))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Mã nhân viên");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(10, 186, 88, 19);

        txfIDCustomerBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfIDCustomerBill.setName("txfIDCustomerBill"); // NOI18N
        jPanel5.add(txfIDCustomerBill);
        txfIDCustomerBill.setBounds(163, 97, 203, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Mã khách hàng");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 97, 100, 19);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Tên khách hàng");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 143, 106, 19);

        txfNameCustomerBill.setEditable(false);
        txfNameCustomerBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(txfNameCustomerBill);
        txfNameCustomerBill.setBounds(164, 140, 202, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Thuế VAT");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 224, 67, 19);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Trị giá");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(10, 310, 40, 19);

        txfTotalPriceBill.setEditable(false);
        txfTotalPriceBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(txfTotalPriceBill);
        txfTotalPriceBill.setBounds(163, 307, 203, 25);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Tổng tiền");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(10, 353, 67, 19);

        txfTotalPayBill.setEditable(false);
        txfTotalPayBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(txfTotalPayBill);
        txfTotalPayBill.setBounds(163, 350, 203, 25);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Số hóa đơn");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(10, 11, 75, 19);

        txfIDBill.setEditable(false);
        txfIDBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(txfIDBill);
        txfIDBill.setBounds(163, 11, 203, 25);

        jDChBillDate.setDateFormatString("dd-MM-yyyy");
        jDChBillDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(jDChBillDate);
        jDChBillDate.setBounds(163, 54, 203, 20);

        cbIDStaffBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbIDStaffBill.setName("cbIDStaffBill"); // NOI18N
        jPanel5.add(cbIDStaffBill);
        cbIDStaffBill.setBounds(163, 183, 203, 25);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Ngày hóa đơn");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(10, 55, 93, 19);

        txfVATBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(txfVATBill);
        txfVATBill.setBounds(163, 221, 203, 25);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("Khuyến mãi");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(10, 267, 77, 19);

        cbDiscountBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbDiscountBill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(cbDiscountBill);
        cbDiscountBill.setBounds(163, 264, 203, 25);

        jPanel1.setLayout(null);

        jDChSearchBill.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(jDChSearchBill);
        jDChSearchBill.setBounds(10, 32, 211, 20);

        btnSearchBill.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSearchBill.setText("TÌM KIẾM");
        btnSearchBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchBill);
        btnSearchBill.setBounds(268, 25, 101, 27);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Tìm hóa đơn theo thời gian");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 2, 202, 19);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sach3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(661, 661, 661)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        jTabbedPane1.addTab("Lập hóa đơn", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(-10, 0, 870, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Date Today = new java.util.Date();
    public void ClearTextBill()
    {
        txfIDBill.setText("");
        jDChBillDate.setDate(Today);
        txfIDCustomerBill.setText("");
        txfNameCustomerBill.setText("");
        txfTotalPriceBill.setText("");
        txfTotalPayBill.setText("");
        txfVATBill.setText("");
    }
    
    //Thêm hóa đơn
    public void InsertBill()
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String BillDate = formatter.format(jDChBillDate.getDate());
        
        int IDCustomer;
        if(txfIDCustomerBill.getText().equals(""))
            IDCustomer = 0;
        else IDCustomer = Integer.parseInt(txfIDCustomerBill.getText());
        
        int IDStaff = Integer.parseInt(cbIDStaffBill.getSelectedItem().toString());
        float VAT = Float.parseFloat(txfVATBill.getText());
        
        if(billBILL.InsertBill(BillDate, IDCustomer, IDStaff, VAT))
        {
            JOptionPane.showMessageDialog(this, "Thêm thành công hóa đơn");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Thêm thất bại hóa đơn");
        }
    }
    //Cập nhật hóa đơn
    public void UpdateBill()
    {
        int IDBill = Integer.parseInt(txfIDBill.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String BillDate = formatter.format(jDChBillDate.getDate());
        
        int IDCustomer;
        if(txfIDCustomerBill.getText().toString().equals(""))
            IDCustomer = 0;
        else IDCustomer = Integer.parseInt(txfIDCustomerBill.getText());
        
        int IDStaff = Integer.parseInt(cbIDStaffBill.getSelectedItem().toString());
        float VAT = Float.parseFloat(txfVATBill.getText());
        
        if(billBILL.UpdateBill(IDBill, BillDate, IDCustomer, IDStaff, VAT))
        {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công hóa đơn");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại hóa đơn");
        }
    }
    
    //Xóa hóa đơn
    public void DeleteBill()
    {
        int IDBill = Integer.parseInt(txfIDBill.getText());
        if(billBILL.DeleteBill(IDBill))
            JOptionPane.showMessageDialog(this, "Xóa thành công hóa đơn");
        else
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
    }
    
    //Tìm hóa đơn theo ngày
    
    
    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
        // TODO add your handling code here:
        ClearTextBill();
        btnAddBill.setEnabled(false);
        btnDelBill.setEnabled(false);
        btnEditBill.setEnabled(false);
        btnSaveBill.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddBillActionPerformed

    private void btnSaveBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillActionPerformed
        // TODO add your handling code here:
        if(flag == 1)
        {     
           InsertBill();
           btnAddBill.setEnabled(true);
           btnEditBill.setEnabled(true);
           btnDelBill.setEnabled(true);
           btnSaveBill.setEnabled(false);
           control.bindingBill(jTableBill, billBILL.LoadBill());
           ClearTextBill();
        }
        if(flag == 2)
        {
            UpdateBill();
            btnAddBill.setEnabled(true);
            btnEditBill.setEnabled(true);
            btnDelBill.setEnabled(true);
            btnSaveBill.setEnabled(false);
            control.bindingBill(jTableBill, billBILL.LoadBill());
            ClearTextBill();
        }
        if(flag == 3)
        {
            DeleteBill();
            btnAddBill.setEnabled(true);
            btnEditBill.setEnabled(true);
            btnDelBill.setEnabled(true);
            btnSaveBill.setEnabled(false);
            control.bindingBill(jTableBill, billBILL.LoadBill());
            ClearTextBill();
        }
    }//GEN-LAST:event_btnSaveBillActionPerformed

    private void btnEditBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBillActionPerformed
        // TODO add your handling code here:
        btnAddBill.setEnabled(false);
        btnDelBill.setEnabled(false);
        btnEditBill.setEnabled(false);
        btnSaveBill.setEnabled(true);
        flag = 2;
    }//GEN-LAST:event_btnEditBillActionPerformed

    private void btnDelBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelBillActionPerformed
        // TODO add your handling code here:
        btnAddBill.setEnabled(false);
        btnDelBill.setEnabled(false);
        btnEditBill.setEnabled(false);
        btnSaveBill.setEnabled(true);
        flag = 3;
    }//GEN-LAST:event_btnDelBillActionPerformed

    private void jTableBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBillMouseClicked
        // TODO add your handling code here:
//         String bookcategogy =jTableBookInfo.getValueAt(row, 1).toString();
//        if(jTableBookInfo.getValueAt(row, 1).toString().equals(bookcategogy))
//        cbNameCategogyBookInfo.setSelectedItem(bookcategogy);
//        
        int row = jTableBill.getSelectedRow();
        txfIDBill.setText(jTableBill.getValueAt(row, 0).toString());
        jDChBillDate.setDate((Date) jTableBill.getModel().getValueAt(row, 1));
        txfIDCustomerBill.setText(jTableBill.getValueAt(row, 2).toString());
        

        cbIDStaffBill.setSelectedItem(jTableBill.getValueAt(row, 3).toString());
        txfVATBill.setText(jTableBill.getValueAt(row, 4).toString());
        txfTotalPriceBill.setText(jTableBill.getValueAt(row, 5).toString());
        txfTotalPayBill.setText(jTableBill.getValueAt(row, 6).toString());
    }//GEN-LAST:event_jTableBillMouseClicked

    private void btnSearchBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBillActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date search = jDChSearchBill.getDate();
        String key;
        if(jDChSearchBill.getDate() == null)
        key = "";
        else
        key = formatter.format(search);
        control.bindingBill(jTableBill, billBILL.SearchBill(key));
        jDChSearchBill.setDate(null);
    }//GEN-LAST:event_btnSearchBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnAddBillInfo;
    private javax.swing.JButton btnDelBill;
    private javax.swing.JButton btnDelBillInfo;
    private javax.swing.JButton btnEditBill;
    private javax.swing.JButton btnEditBillInfo;
    private javax.swing.JButton btnPayBillInfo;
    private javax.swing.JButton btnPrintBillInfo;
    private javax.swing.JButton btnSaveBill;
    private javax.swing.JButton btnSaveBillInfo;
    private javax.swing.JButton btnSearchBill;
    private javax.swing.JComboBox<String> cbAmountBillInfo;
    private javax.swing.JComboBox<String> cbDiscountBill;
    private javax.swing.JComboBox<String> cbIDBill_BillInfo;
    private javax.swing.JComboBox<String> cbIDStaffBill;
    private com.toedter.calendar.JDateChooser jDChBillDate;
    private com.toedter.calendar.JDateChooser jDChSearchBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBill;
    private javax.swing.JTable jTableBillInfo;
    private javax.swing.JTextField txfCashBillInfo;
    private javax.swing.JTextField txfDiscountBillInfo;
    private javax.swing.JTextField txfIDBill;
    private javax.swing.JTextField txfIDBookBillInfo;
    private javax.swing.JTextField txfIDCustomerBill;
    private javax.swing.JTextField txfNameCustomerBill;
    private javax.swing.JTextField txfPriceBillInfo;
    private javax.swing.JTextField txfRepayBillInfo;
    private javax.swing.JTextField txfTotalPayBill;
    private javax.swing.JTextField txfTotalPayBillInfo;
    private javax.swing.JTextField txfTotalPriceBill;
    private javax.swing.JTextField txfTotalPriceBillInfo;
    private javax.swing.JTextField txfVATBill;
    private javax.swing.JTextField txfVATBillInfo;
    // End of variables declaration//GEN-END:variables
}
