/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.BookBLL;
import  Entity.Distributor;
import DAL.DistributorDAL;
import  Utilties.ControlFormat;
import BLL.DistributorBLL;
import BLL.BookStockBLL;
import BLL.BookStockDetailBLL;
import Entity.Book;
import Entity.BookStock;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author STIREN
 */
public class fStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form fStock
     */
    private int flag=0;
    ControlFormat control =new ControlFormat();
    DistributorBLL distributorBLL=new DistributorBLL();
    BookStockBLL bookStockBLL=new BookStockBLL();
    BookBLL bookbll =new BookBLL();
    BookStockDetailBLL bookStockDetailBLL =new BookStockDetailBLL();
    public fStock() {
        initComponents();
        Toolkit tk =Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();
        jPanel1.setSize(x, y);
        jPanel2.setSize(x,y);
        jPanel3.setSize(x, y);
        jLabel6.setSize((int)jPanel1.getSize().getWidth(), (int)jPanel1.getSize().getHeight());
        jLabel9.setSize((int)jPanel3.getSize().getWidth(), (int)jPanel3.getSize().getHeight());
        jLabel19.setSize((int)jPanel2.getSize().getWidth(), (int)jPanel2.getSize().getHeight());
        control.bindingDistributor(jTableDistributorInfo,distributorBLL.LoadDistributor());
        control.bindingBookStock(jTableStock, bookStockBLL.LoadBookStock());
        control.bindingBookStockDetail(jTableStockInfo, bookStockDetailBLL.LoadBookStockDetail());
        Date date =new Date();
        jDateChooserStock.setDate(date);
        cbNameDistributorStock.removeAllItems();
        for(Distributor distributor: distributorBLL.LoadDistributor())
        {
            cbNameDistributorStock.addItem(distributor.getNameDistributor());
        }
        cbIDStockInfo.removeAllItems();;
        for(BookStock bookstock :bookStockBLL.LoadBookStock())
        {
            String s =String.valueOf(bookstock.getIDBookStock());
            cbIDStockInfo.addItem(s);
        }
        cbNameBookStockInfo.removeAllItems();
        for(Book book: bookbll.LoadBook())
        {
            cbNameBookStockInfo.addItem(book.getNameBook());
        }
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txfSearchDistributorStock = new javax.swing.JTextField();
        btnSearchDistributorStock = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfIDDistributorInfo = new javax.swing.JTextField();
        txfNameDistributorInfo = new javax.swing.JTextField();
        txfAddressDistributorInfo = new javax.swing.JTextField();
        txfPhoneDistributorInfo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAddDistributorInfo = new javax.swing.JButton();
        btnEditDistributorInfo = new javax.swing.JButton();
        btnSaveDistributorInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDistributorInfo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txfSearchStock = new javax.swing.JTextField();
        btnSearchStock = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfIDStock = new javax.swing.JTextField();
        jDateChooserStock = new com.toedter.calendar.JDateChooser();
        cbNameDistributorStock = new javax.swing.JComboBox<>();
        txfTotalStock = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnAddStock = new javax.swing.JButton();
        btnEditStock = new javax.swing.JButton();
        btnDelStock = new javax.swing.JButton();
        btnSaveStock = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStock = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txfSearchStockInfo = new javax.swing.JTextField();
        btnSearchStockInfo = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txfAmountStockInfo = new javax.swing.JTextField();
        cbIDStockInfo = new javax.swing.JComboBox<>();
        cbNameBookStockInfo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txfAmount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txfCost = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btnAddStockInfo = new javax.swing.JButton();
        btnEditStockInfo = new javax.swing.JButton();
        btnDelStockInfo = new javax.swing.JButton();
        btnSaveStockInfo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableStockInfo = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("QUẢN LÝ NHẬP SÁCH");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("QUẢN LÍ THÔNG TIN NHÀ CUNG CẤP SÁCH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(159, 53, 647, 37);

        jPanel4.setOpaque(false);

        txfSearchDistributorStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchDistributorStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchDistributorStock.setText("Tìm kiếm");
        btnSearchDistributorStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDistributorStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfSearchDistributorStock, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnSearchDistributorStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchDistributorStock)
                    .addComponent(txfSearchDistributorStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 101, 387, 66);

        jPanel5.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã nhà cung cấp");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên nhà cung cấp");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Số điện thoại");

        txfIDDistributorInfo.setEditable(false);
        txfIDDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfNameDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfAddressDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfPhoneDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfIDDistributorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(txfNameDistributorInfo)
                    .addComponent(txfAddressDistributorInfo)
                    .addComponent(txfPhoneDistributorInfo))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfIDDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfNameDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfAddressDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfPhoneDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 193, 428, 201);

        jPanel6.setOpaque(false);

        btnAddDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddDistributorInfo.setText("THÊM");
        btnAddDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDistributorInfoActionPerformed(evt);
            }
        });

        btnEditDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditDistributorInfo.setText("CẬP NHẬT");
        btnEditDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDistributorInfoActionPerformed(evt);
            }
        });

        btnSaveDistributorInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveDistributorInfo.setText("LƯU");
        btnSaveDistributorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDistributorInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDistributorInfo)
                .addGap(42, 42, 42)
                .addComponent(btnEditDistributorInfo)
                .addGap(61, 61, 61)
                .addComponent(btnSaveDistributorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDistributorInfo)
                    .addComponent(btnEditDistributorInfo)
                    .addComponent(btnSaveDistributorInfo))
                .addContainerGap())
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(39, 447, 399, 47);

        jTableDistributorInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableDistributorInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại", "Email"
            }
        ));
        jTableDistributorInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDistributorInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDistributorInfo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(540, 193, 515, 407);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bia7.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-30, 0, 1280, 710);

        jTabbedPane1.addTab("Nhà cung cấp sách", jPanel1);

        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("QUẢN LÝ PHIẾU NHẬP SÁCH");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(423, 57, 430, 37);

        jPanel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel7.setOpaque(false);

        txfSearchStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchStock.setText("Tìm kiếm");
        btnSearchStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfSearchStock, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchStock)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearchStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStock))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 112, 451, 54);

        jPanel8.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ngày nhập");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tổng tiền");

        txfIDStock.setEditable(false);
        txfIDStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jDateChooserStock.setDateFormatString("dd-MM-yyyy");
        jDateChooserStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cbNameDistributorStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfTotalStock.setEditable(false);
        txfTotalStock.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tên nhà cung cấp");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Số phiếu nhập");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfTotalStock, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txfIDStock)
                                .addComponent(jDateChooserStock, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(cbNameDistributorStock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel10))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfIDStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(jDateChooserStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cbNameDistributorStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txfTotalStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);
        jPanel8.setBounds(10, 197, 393, 243);

        jPanel9.setOpaque(false);

        btnAddStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddStock.setText("THÊM");
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        btnEditStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditStock.setText("CẬP NHẬT");
        btnEditStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStockActionPerformed(evt);
            }
        });

        btnDelStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelStock.setText("XÓA");
        btnDelStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStockActionPerformed(evt);
            }
        });

        btnSaveStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveStock.setText("LƯU");
        btnSaveStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddStock)
                .addGap(31, 31, 31)
                .addComponent(btnEditStock)
                .addGap(31, 31, 31)
                .addComponent(btnDelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveStock, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStock)
                    .addComponent(btnEditStock)
                    .addComponent(btnDelStock)
                    .addComponent(btnSaveStock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9);
        jPanel9.setBounds(10, 458, 426, 47);

        jTableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số phiếu nhập", "Ngày nhập", "Mã nhà cung cấp", "Tên nhà cung cấp", "Tổng tiền"
            }
        ));
        jTableStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStockMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableStock);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(652, 197, 554, 402);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bia7.jpg"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(-20, 0, 1260, 690);

        jTabbedPane1.addTab("Phiếu nhập sách", jPanel2);

        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setText("QUẢN LÍ CHI TIẾT PHIẾU NHẬP SÁCH");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(417, 55, 570, 37);

        jPanel10.setOpaque(false);

        txfSearchStockInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchStockInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchStockInfo.setText("Tìm kiếm");
        btnSearchStockInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStockInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfSearchStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchStockInfo)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearchStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStockInfo))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel10);
        jPanel10.setBounds(10, 110, 360, 57);

        jPanel11.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Số phiếu nhập");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Tên sách");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Số lượng");

        txfAmountStockInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cbIDStockInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cbNameBookStockInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbNameBookStockInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Thành tiền");

        txfAmount.setEditable(false);
        txfAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Giá nhập");

        txfCost.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfCost, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txfAmountStockInfo)
                        .addComponent(cbIDStockInfo, 0, 216, Short.MAX_VALUE)
                        .addComponent(cbNameBookStockInfo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbNameBookStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(cbIDStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txfAmountStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txfCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jPanel3.add(jPanel11);
        jPanel11.setBounds(10, 185, 374, 200);

        jPanel12.setOpaque(false);

        btnAddStockInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddStockInfo.setText("THÊM");
        btnAddStockInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockInfoActionPerformed(evt);
            }
        });

        btnEditStockInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditStockInfo.setText("CẬP NHẬT");
        btnEditStockInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStockInfoActionPerformed(evt);
            }
        });

        btnDelStockInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelStockInfo.setText("XÓA");
        btnDelStockInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStockInfoActionPerformed(evt);
            }
        });

        btnSaveStockInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveStockInfo.setText("LƯU");
        btnSaveStockInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStockInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditStockInfo)
                .addGap(18, 18, 18)
                .addComponent(btnDelStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveStockInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStockInfo)
                    .addComponent(btnEditStockInfo)
                    .addComponent(btnDelStockInfo)
                    .addComponent(btnSaveStockInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel12);
        jPanel12.setBounds(18, 403, 438, 47);

        jTableStockInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableStockInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số phiếu nhập", "Mã sách", "Số lượng", "Thành tiền"
            }
        ));
        jTableStockInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStockInfoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableStockInfo);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(616, 185, 527, 402);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bia7.jpg"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(-10, 0, 1240, 700);

        jTabbedPane1.addTab("Chi tiết phiếu nhập sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDistributorInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDistributorInfoMouseClicked
        // TODO add your handling code here:
        int row=jTableDistributorInfo.getSelectedRow();
        txfIDDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 0).toString());
        txfNameDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 1).toString());
        txfAddressDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 2).toString());
        txfPhoneDistributorInfo.setText(jTableDistributorInfo.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTableDistributorInfoMouseClicked

    private void btnAddDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDistributorInfoActionPerformed
        // TODO add your handling code here:
        ClearTextDistibutor();
        btnAddDistributorInfo.setEnabled(false);
        btnEditDistributorInfo.setEnabled(false);
        btnSaveDistributorInfo.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddDistributorInfoActionPerformed

    private void btnSaveDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDistributorInfoActionPerformed
        // TODO add your handling code here:
        if(flag==1)
        {
            if(InsertDistributor()==true)
            {
                control.bindingDistributor(jTableDistributorInfo, distributorBLL.LoadDistributor());
            }
            btnAddDistributorInfo.setEnabled(true);
            btnEditDistributorInfo.setEnabled(true);
            btnSaveDistributorInfo.setEnabled(false);
        }
        if(flag==2)
        {
            if(UpdateDistributor()==true)
            {
                control.bindingDistributor(jTableDistributorInfo, distributorBLL.LoadDistributor());
            }
            btnAddDistributorInfo.setEnabled(true);
            btnEditDistributorInfo.setEnabled(true);
            btnSaveDistributorInfo.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveDistributorInfoActionPerformed

    private void btnEditDistributorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDistributorInfoActionPerformed
        // TODO add your handling code here:
        btnAddDistributorInfo.setEnabled(false);
        btnEditDistributorInfo.setEnabled(false);
        btnSaveDistributorInfo.setEnabled(true);
        flag=2;
    }//GEN-LAST:event_btnEditDistributorInfoActionPerformed

    private void btnSearchDistributorStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDistributorStockActionPerformed
        // TODO add your handling code here:
        String key=txfSearchDistributorStock.getText();
        control.bindingDistributor(jTableDistributorInfo, distributorBLL.SearchDistributor(key));
        txfSearchDistributorStock.setText("");
    }//GEN-LAST:event_btnSearchDistributorStockActionPerformed

    private void jTableStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStockMouseClicked
        // TODO add your handling code here:
        int row=jTableStock.getSelectedRow();
        txfIDStock.setText(jTableStock.getValueAt(row, 0).toString());
        jDateChooserStock.setDate((Date)jTableStock.getModel().getValueAt(row, 1));
        String NameDistributor =jTableStock.getValueAt(row, 2).toString();
        if(jTableStock.getValueAt(row, 2).toString().equals(NameDistributor))
            cbNameDistributorStock.setSelectedItem(NameDistributor);
        txfTotalStock.setText(jTableStock.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTableStockMouseClicked

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
        // TODO add your handling code here:
        ClearTextBookStock();
        btnAddStock.setEnabled(false);
        btnEditStock.setEnabled(false);
        btnDelStock.setEnabled(false);
        btnSaveStock.setEnabled(true);
        flag=4;
    }//GEN-LAST:event_btnAddStockActionPerformed

    private void btnEditStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStockActionPerformed
        // TODO add your handling code here:
        btnAddStock.setEnabled(false);
        btnEditStock.setEnabled(false);
        btnDelStock.setEnabled(false);
        btnSaveStock.setEnabled(true);
        flag=5;
    }//GEN-LAST:event_btnEditStockActionPerformed

    private void btnDelStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStockActionPerformed
        // TODO add your handling code here:
        btnAddStock.setEnabled(false);
        btnEditStock.setEnabled(false);
        btnDelStock.setEnabled(false);
        btnSaveStock.setEnabled(true);
        flag=6;
    }//GEN-LAST:event_btnDelStockActionPerformed

    private void btnSaveStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStockActionPerformed
        // TODO add your handling code here:
        if(flag==4)
        {
            if(InsertBookStock()==true)
            {
            control.bindingBookStock(jTableStock, bookStockBLL.LoadBookStock());
            }
            btnAddStock.setEnabled(true);
            btnEditStock.setEnabled(true);
            btnDelStock.setEnabled(true);
            btnSaveStock.setEnabled(false);
        }
        if(flag==5)
        {
            if(UpdateBookStock()==true)
            {
            control.bindingBookStock(jTableStock, bookStockBLL.LoadBookStock());
            }
            btnAddStock.setEnabled(true);
            btnEditStock.setEnabled(true);
            btnDelStock.setEnabled(true);
            btnSaveStock.setEnabled(false);
        }
        if(flag==6)
        {
            if(DeleteBookStock()==true)
            {
                control.bindingBookStock(jTableStock, bookStockBLL.LoadBookStock());
            }
            btnAddStock.setEnabled(true);
            btnEditStock.setEnabled(true);
            btnDelStock.setEnabled(true);
            btnSaveStock.setEnabled(false);
           
        }
    }//GEN-LAST:event_btnSaveStockActionPerformed

    private void btnSearchStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStockActionPerformed
        // TODO add your handling code here:
        String key =txfSearchStock.getText();
        control.bindingBookStock(jTableStock, bookStockBLL.SearchBookStock(key));
        txfSearchStock.setText("");
            
    }//GEN-LAST:event_btnSearchStockActionPerformed

    private void jTableStockInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStockInfoMouseClicked
        // TODO add your handling code here:
        int row=jTableStockInfo.getSelectedRow();
        int IDBookStock =Integer.parseInt(jTableStockInfo.getValueAt(row, 0).toString());
        if(Integer.parseInt(jTableStockInfo.getValueAt(row, 0).toString())==IDBookStock)
            cbIDStockInfo.setSelectedItem(IDBookStock);
        String NameBook =jTableStockInfo.getValueAt(row, 1).toString();
        if(jTableStockInfo.getValueAt(row, 1).equals(NameBook))
            cbNameBookStockInfo.setSelectedItem(NameBook);
        txfAmountStockInfo.setText(jTableStockInfo.getValueAt(row, 2).toString());
        txfCost.setText(jTableStockInfo.getValueAt(row, 3).toString());
        txfAmount.setText(jTableStockInfo.getValueAt(row, 4).toString());
        
    }//GEN-LAST:event_jTableStockInfoMouseClicked

    public void ClearTextStockInfo()
    {
        cbIDStockInfo.setSelectedIndex(0);
        cbNameBookStockInfo.setSelectedIndex(0);
        txfAmountStockInfo.setText("");
        txfCost.setText("");
        txfAmount.setText("");
    }
    private void btnAddStockInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockInfoActionPerformed
        // TODO add your handling code here:
        ClearTextStockInfo();
        btnAddStockInfo.setEnabled(false);
        btnEditStockInfo.setEnabled(false);
        btnDelStockInfo.setEnabled(false);
        btnSaveStockInfo.setEnabled(true);
        flag=7;
    }//GEN-LAST:event_btnAddStockInfoActionPerformed

    private void btnEditStockInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStockInfoActionPerformed
        // TODO add your handling code here:
        btnAddStockInfo.setEnabled(false);
        btnEditStockInfo.setEnabled(false);
        btnDelStockInfo.setEnabled(false);
        btnSaveStockInfo.setEnabled(true);
        flag=8;
    }//GEN-LAST:event_btnEditStockInfoActionPerformed

    private void btnDelStockInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStockInfoActionPerformed
        // TODO add your handling code here:
        btnAddStockInfo.setEnabled(false);
        btnEditStockInfo.setEnabled(false);
        btnDelStockInfo.setEnabled(false);
        btnSaveStockInfo.setEnabled(true);
        flag=9;
    }//GEN-LAST:event_btnDelStockInfoActionPerformed

    private void btnSaveStockInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStockInfoActionPerformed
        // TODO add your handling code here:
        if(flag==7)
        {
            if(InsertBookStockDetail()==true)
            {
                control.bindingBookStockDetail(jTableStockInfo, bookStockDetailBLL.LoadBookStockDetail());
                control.bindingBookStock(jTableStock, bookStockBLL.LoadBookStock());
            }
            btnAddStockInfo.setEnabled(true);
            btnEditStockInfo.setEnabled(true);
            btnDelStockInfo.setEnabled(true);
            btnSaveStockInfo.setEnabled(false);
        }
        if(flag==8)
        {
            if(UpdateBookStockDetail()==true)
            {
                control.bindingBookStockDetail(jTableStockInfo, bookStockDetailBLL.LoadBookStockDetail());
                control.bindingBookStock(jTableStock, bookStockBLL.LoadBookStock());
            }
            btnAddStockInfo.setEnabled(true);
            btnEditStockInfo.setEnabled(true);
            btnDelStockInfo.setEnabled(true);
            btnSaveStockInfo.setEnabled(false);
        }
        if(flag==9)
        {
            if(DeleteBookStockDetail()==true)
            {
                control.bindingBookStockDetail(jTableStockInfo, bookStockDetailBLL.LoadBookStockDetail());
                control.bindingBookStock(jTableStock, bookStockBLL.LoadBookStock());
            }
            btnAddStockInfo.setEnabled(true);
            btnEditStockInfo.setEnabled(true);
            btnDelStockInfo.setEnabled(true);
            btnSaveStockInfo.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveStockInfoActionPerformed

    private void btnSearchStockInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStockInfoActionPerformed
        // TODO add your handling code here:
        int key =Integer.parseInt(txfSearchStockInfo.getText().toString());
        control.bindingBookStockDetail(jTableStockInfo,bookStockDetailBLL.SearchBookStockDetail(key));
        txfSearchStockInfo.setText("");
        
    }//GEN-LAST:event_btnSearchStockInfoActionPerformed
    public void ClearTextDistibutor()
    {
        txfIDDistributorInfo.setText("");
        txfNameDistributorInfo.setText("");
        txfAddressDistributorInfo.setText("");
        txfPhoneDistributorInfo.setText("");
    }
    public boolean InsertDistributor()
    {
        String NameDistributor =txfNameDistributorInfo.getText().toString();
        String Address =txfAddressDistributorInfo.getText().toString();
        String PhoneNumber =txfPhoneDistributorInfo.getText().toString();
        if(txfNameDistributorInfo.getText().toString().equals("")|| txfPhoneDistributorInfo.getText().toString().equals("") || txfAddressDistributorInfo.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, địa chỉ, số điện thoại là bắt buộc");
            return false;
        }
        else
        {
            if(distributorBLL.InsertDistributor(NameDistributor, Address, PhoneNumber))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công nhà cung cấp");
                return true;
            }   
                else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
        }
        
    }
    public boolean UpdateDistributor()
    {
        int IDDistributor=Integer.parseInt(txfIDDistributorInfo.getText().toString());
        String NameDistributor =txfNameDistributorInfo.getText().toString();
        String Address =txfAddressDistributorInfo.getText().toString();
        String PhoneNumber =txfPhoneDistributorInfo.getText().toString();
        if(txfNameDistributorInfo.getText().toString().equals("")|| txfPhoneDistributorInfo.getText().toString().equals("") || txfAddressDistributorInfo.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, địa chỉ, số điện thoại là bắt buộc");
            return false;
        }
        else
        {
            if(distributorBLL.UpdateDistributor(IDDistributor,NameDistributor, Address, PhoneNumber))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công nhà cung cấp");
                return true;
            }   
                else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
        }
    }
      public void ClearTextBookStock()
    {
        txfIDStock.setText("");
        txfTotalStock.setText("");
    }
    public boolean InsertBookStock()
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date DateStock=jDateChooserStock.getDate();
        String strDateStock = formatter.format(DateStock);
        String NameDistributor =cbNameDistributorStock.getSelectedItem().toString();
        int IDDistributor=distributorBLL.getIDDistributor(NameDistributor);
        if(NameDistributor.equals("") || strDateStock.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, ngày nhập, thành tiền là các trường bắt buộc");
            return false;
        }
        else
        {
            if(bookStockBLL.InsertBookStock(strDateStock, IDDistributor))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
            
        }
        
        
    }
    public boolean  UpdateBookStock()
    {
        int IDBookStock =Integer.parseInt(txfIDStock.getText().toString());
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date DateStock=jDateChooserStock.getDate();
        String strDateStock = formatter.format(DateStock);
        String NameDistributor =cbNameDistributorStock.getSelectedItem().toString();
        int IDDistributor=distributorBLL.getIDDistributor(NameDistributor);
        float TotalStock=Float.parseFloat(txfTotalStock.getText().toString());
        if(NameDistributor.equals("") || strDateStock.equals("")|| txfTotalStock.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp, ngày nhập, thành tiền là các trường bắt buộc");
            return false;
        }
        else
        {
            if(bookStockBLL.UpdateBookStock(IDBookStock, strDateStock, IDDistributor))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
            
        }
        
    }
    public boolean DeleteBookStock()
    {
        int IDBookStock =Integer.parseInt(txfIDStock.getText().toString());
         if(bookStockBLL.DeleteBookStock(IDBookStock))
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
                return false;
            }
    }
    public boolean InsertBookStockDetail()
    {
        int IDBookStock=Integer.parseInt(cbIDStockInfo.getSelectedItem().toString());
        String NameBook =cbNameBookStockInfo.getSelectedItem().toString();
        int IDBook=bookbll.getIDBook(NameBook);
        int AmountStock=Integer.parseInt(txfAmountStockInfo.getText().toString());
        float Cost =Float.parseFloat(txfCost.getText().toString());
        if(String.valueOf(IDBookStock).equals("")|| NameBook.equals("") ||txfAmountStockInfo.equals("")|| txfCost.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nhập thông tin chưa đầy đủ");
            return false;
        }
       else
        {
            if(bookStockDetailBLL.InsertBookStockDetail(IDBookStock, IDBook, AmountStock,Cost))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return false;
            }
        }
    }
    public boolean  UpdateBookStockDetail()
    {
        int IDBookStock=Integer.parseInt(cbIDStockInfo.getSelectedItem().toString());
        String NameBook =cbNameBookStockInfo.getSelectedItem().toString();
        int IDBook=bookbll.getIDBook(NameBook);
        int AmountStock=Integer.parseInt(txfAmountStockInfo.getText());
        float Cost=Float.parseFloat(txfCost.getText());
        if(String.valueOf(IDBookStock).equals("")|| NameBook.equals("")||txfAmountStockInfo.equals("")|| txfCost.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nhập thông tin chưa đầy đủ");
            return false;
        }
       else
        {
            if(bookStockDetailBLL.UpdateBookStockDetail(IDBookStock, IDBook, AmountStock,Cost))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return false;
            }
        }
     
    }
    public boolean DeleteBookStockDetail()
    {
       int IDBookStock=Integer.parseInt(cbIDStockInfo.getSelectedItem().toString());
       String NameBook=cbNameBookStockInfo.getSelectedItem().toString();
       int IDBook =bookbll.getIDBook(NameBook);
       if(bookStockDetailBLL.DeleteBookStockDetail(IDBookStock,IDBook))
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công chi tiết phiếu nhập sách");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
                return false;
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDistributorInfo;
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnAddStockInfo;
    private javax.swing.JButton btnDelStock;
    private javax.swing.JButton btnDelStockInfo;
    private javax.swing.JButton btnEditDistributorInfo;
    private javax.swing.JButton btnEditStock;
    private javax.swing.JButton btnEditStockInfo;
    private javax.swing.JButton btnSaveDistributorInfo;
    private javax.swing.JButton btnSaveStock;
    private javax.swing.JButton btnSaveStockInfo;
    private javax.swing.JButton btnSearchDistributorStock;
    private javax.swing.JButton btnSearchStock;
    private javax.swing.JButton btnSearchStockInfo;
    private javax.swing.JComboBox<String> cbIDStockInfo;
    private javax.swing.JComboBox<String> cbNameBookStockInfo;
    private javax.swing.JComboBox<String> cbNameDistributorStock;
    private com.toedter.calendar.JDateChooser jDateChooserStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDistributorInfo;
    private javax.swing.JTable jTableStock;
    private javax.swing.JTable jTableStockInfo;
    private javax.swing.JTextField txfAddressDistributorInfo;
    private javax.swing.JTextField txfAmount;
    private javax.swing.JTextField txfAmountStockInfo;
    private javax.swing.JTextField txfCost;
    private javax.swing.JTextField txfIDDistributorInfo;
    private javax.swing.JTextField txfIDStock;
    private javax.swing.JTextField txfNameDistributorInfo;
    private javax.swing.JTextField txfPhoneDistributorInfo;
    private javax.swing.JTextField txfSearchDistributorStock;
    private javax.swing.JTextField txfSearchStock;
    private javax.swing.JTextField txfSearchStockInfo;
    private javax.swing.JTextField txfTotalStock;
    // End of variables declaration//GEN-END:variables
}
